### PR TITLE
🔄🔐 refactor: auth; style: match OpenAI; feat: custom social login order

### PR DESCRIPTION
**Pull request by berry-13**
### before

image

### after

image

### before

https://github.com/danny-avila/LibreChat/assets/81851188/b59f6978-a5d1-421e-ab25-8c78df6cbf67

### after

https://github.com/danny-avila/LibreChat/assets/81851188/1e155d0c-d40b-4535-b7a6-5427e28b3af7

## Change Type

- [x] refactor

## Testing

check if login, registration, social login and social registration works correctly
tested every possible .env variable settings

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.

### CODE REVIEW

**Comment by danny-avila** [comment]
Is this still WIP?

**Comment by Berry-13** [comment]
> Is this still WIP?

I only need to describe what I changed

**Comment by danny-avila** [comment]
> > Is this still WIP?
> 
> I only need to describe what I changed

Agreed, thanks for doing that!

**Comment by danny-avila** [comment]
thanks for doing this. can you resolve the conflict so I can merge?

**Comment by Berry-13** [comment]
> thanks for doing this. can you resolve the conflict so I can merge?

done

**Comment by danny-avila** [comment]
going to refactor this a bit to use the new config file instead

**Review by danny-avila — APPROVED** [review]

**Pull request merged**
