### PR TITLE
🔒 feat: password reset disable option; fix: account email error message

### LINKED ISSUE #2326: Enhancement: Option to disable password reset functionality entirely
### What features would you like to see added?

I'd rather disable the password reset functionality entirely, since I don't need it and it's a potential vector for attack. It would be great if there was an option to disable it.

### More details

My concerns:
1. The default is the insecure password reset link, which I fear will lead to folks getting compromised.
2. The email flow leaks account emails by complaining when an incorrect email address is entered.

### Which components are impacted by your request?

_No response_

### Pictures

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by berry-13**
## Summary

feat: Implement a disable option for password reset
fix: resolved the error message regarding incorrect account email

### before:

image

image

### after:

image

image

this way no one can understand if the user it's registred or not, even by looking at the status code

## Change Type

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation update

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.
- [x] New documents have been locally validated with mkdocs

### CODE REVIEW

**Comment by XHyperDEVX** [comment]
Will only the option to reset the password be deactivated here or will the "Reset password" option also disappear from the UI?

**Comment by Berry-13** [comment]
> Will only the option to reset the password be deactivated here or will the "Reset password" option also disappear from the UI?

wdym exactly? this disable the password reset from both frontend and backend

**Comment by XHyperDEVX** [comment]
i mean if this hyperlink also disappears or if when you click on it only the message "password reset disabled" is displayed (because i only saw this in the code)
image

**Comment by Berry-13** [comment]
> i mean if this hyperlink also disappears or if when you click on it only the message "password reset disabled" is displayed (because i only saw this in the code)

no no, also that button disappears when disabling the reset password

**Comment by danny-avila** [comment]
@Berry-13 Adjusting the existing, failing tests to match the new behavior looks pretty simple. Please work on this when you get the chance.

**Comment by danny-avila** [comment]
@ohneda I removed the eslint import/order rule in this PR. I noticed since that PR was merged, there has been a noticeable slowdown when saving files, likely due to eslint processing. Also, it was still not ordering it as desired, so it didn't seem worth to include.

**Comment by danny-avila** [comment]
It's enough to update the contributing page:

## 7. Module Import Conventions

- `npm` packages first, 
     - from shortest line (top) to longest (bottom)

- Followed by typescript types (pertains to data-provider and client workspaces)
     - longest line (top) to shortest (bottom)
     - types from package come first

- Lastly, local imports
     - longest line (top) to shortest (bottom)
     - imports with alias `~` treated the same as relative import with respect to line length

**Review by danny-avila — APPROVED** [review]

**Comment by ohneda** [comment]
> @ohneda I removed the eslint import/order rule in this PR. I noticed since that PR was merged, there has been a noticeable slowdown when saving files, likely due to eslint processing. Also, it was still not ordering it as desired, so it didn't seem worth to include.

ok, no problem. Thank you for letting me know!

**Pull request merged**
