### PR TITLE
🤖 feat: Private Assistants

### LINKED ISSUE #1926: Enhancement: Private Assistants
### What features would you like to see added?

Created assistants could be either shared, or private for the author

### More details

Currently, users can access any assistant. This allows other users to access the files uploaded to the assistant. Making assistants private should prevent other users from accessing the files.

### Which components are impacted by your request?

UI

### Pictures

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by danny-avila**
Originally #2831 

Thank you @leon-juenemann 

## Summary

Closes #1926

Adds the option to only see assistants that you (the user) created or that don't have an author. This is important for privacy reasons when multiple users are sharing the same API-Key. Otherwise a user could get personal information from e.g. a file that another user uploaded.

The specific use case that led to this PR:
- we don't want users to see other users assistants
- we still want to make some assistants available to all users (assistants without a metadata.author field)

## Change Type

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Testing

In librechat.yaml:
```
endpoints:
  assistants:
    privateAssistants: true
```
1. Login User1 and create an assistant.
2. Login User2 and does not have access to the assistant.
## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] Local unit tests pass with my changes
- [x] A pull request for updating the documentation has been submitted. (https://github.com/LibreChat-AI/librechat.ai/pull/37)

### CODE REVIEW

**Comment by danny-avila** [comment]
@leon-juenemann I noticed you are including assistants without any author metadata as "private."

In my opinion, these should only be visible by the admin, since they are likely created outside of LibreChat, or before LibreChat was used for Assistants.

I'll be adjusting that, and then wrap up this PR.

**Comment by leon-juenemann** [comment]
> @leon-juenemann I noticed you are including assistants without any author metadata as "private."
> 
> In my opinion, these should only be visible by the admin, since they are likely created outside of LibreChat, or before LibreChat was used for Assistants.
> 
> I'll be adjusting that, and then wrap up this PR.

Yes, this was intentional.
For our use-case we want a way to have some assistants (created outside of LibreChat, e.g. in the Assistants Playground) public to all our users, but assistants that the user created themselves should be private. It's not important were these shared public assistants are created. Just to have some way to do this. 
But I agree that it is maybe not the best solution and could be misunderstood my others with a different usecase.
Perhaps in the future only the admin could see all assistants and could make them public via a toggle button in the UI.

**Comment by danny-avila** [comment]
> > @leon-juenemann I noticed you are including assistants without any author metadata as "private."
> > In my opinion, these should only be visible by the admin, since they are likely created outside of LibreChat, or before LibreChat was used for Assistants.
> > I'll be adjusting that, and then wrap up this PR.
> 
> Yes, this was intentional. For our use-case we want a way to have some assistants (created outside of LibreChat, e.g. in the Assistants Playground) public to all our users, but assistants that the user created themselves should be private. It's not important where these shared public assistants are created. Just to have a way to achieve this distinction. But I agree that it is maybe not the best solution and could be misunderstood my others with a different usecase. Perhaps in the future only the admin could see all assistants and could make them public via a toggle button in the UI.

That use case makes a lot of sense. I have a way to "share" them in mind already, but in the immediate-term, adding back the "undefined" author condition should be simple for you

**Comment by FabianHertwig** [comment]
> I have a way to "share" them in mind already

@danny-avila could you put that in an issue so that we can track the progress? Can we support here?

**Pull request merged**
