### PR TITLE
Feat clean after regenerate pr

### PR DESCRIPTION
**Pull request by wtlyu**

### CODE REVIEW

**Comment by wtlyu** [comment]
Here shows the expected procedure:

1. when submitting, set isSubmitting = true
2. when receiving any message, message.isSubmitting will = true
3. when finished all above isSubmitting=false
4. when cancelled: all above isSubmitting=false, and message.cancel will be true

So for the input:

// Button
if isSubmitting -> show stop generating button
else if latestMessage&&!latestMessage?.isCreatedByUser -> show regenerate button 

// UI
if (!isSubmitting and message.cancel) or error -> disable the input and submit button
else if isSubmitting -> submit button become three dots.

**Comment by wtlyu** [comment]
another bug also fix: when text is not blank, user will never see the placeholder. even message is error or unfinished.

**Comment by danny-avila** [comment]
only issue here is that now it only stops the first message, and submit state doesn't seem to be firing after the first message

**Comment by wtlyu** [comment]
also revert commit [eec7ca3](https://github.com/danny-avila/chatgpt-clone/commit/eec7ca36fd6a48887ea455cf8b3a57da0874a9e8)

which I believe a not a real bugfix.

**Comment by wtlyu** [comment]
> firing

sorry, what do you mean of "it only stops the first message"

**Comment by danny-avila** [comment]
adding `dispatch(setSubmitState(true));` to handleRegenerate and `dispatch(setSubmitState(false));` to handleStopGenerating  seems to take care of it

> > firing
> 
> sorry, what do you mean of "it only stops the first message"

if you send a message to a chat, if it's the first message upon refresh, you will have the 'stop generating' option or button in view. Any subsequent messages do not trigger the stop view

**Comment by danny-avila** [comment]
i could be wrong about the created handling but 'll stop trying to debug this while you're working on it. just reporting the current issue

**Comment by wtlyu** [comment]
sorry, I cannot reproduce. can you give a video on that?

**Comment by revolverinegirl** [comment]
Hello! this is so awesome! good job and sorry to disturb guys, do you have a discord or something to contact?

**Comment by wtlyu** [comment]
> Hello! this is so awesome! good job and sorry to disturb guys, do you have a discord or something to contact?

aha I'm just write a message to @danny-avila asking for a discord or telegram
what a coincidence

**Comment by danny-avila** [comment]
> > Hello! this is so awesome! good job and sorry to disturb guys, do you have a discord or something to contact?
> 
> aha I'm just write a message to @danny-avila asking for a discord or telegram what a coincidence

@revolverinegirl no worries haha at this point just github! i can make a discord now

**Comment by revolverinegirl** [comment]
Yes please! i find this project really exciting and the work you are doing is dope! please send me the link of discord, i will join asap! @wtlyu @danny-avila

**Comment by danny-avila** [comment]
@wtlyu here is a video. sorry its short, using free service

https://gyazo.com/c3b49ae2cb348963898ee2e069398238

**Comment by wtlyu** [comment]
> @wtlyu here is a video. sorry its short, using free service
> 
> https://gyazo.com/c3b49ae2cb348963898ee2e069398238
> 
> im sure to be on your latest branch [feat-clean-after-regenerate-pr](https://github.com/wtlyu/chatgpt-clone/tree/feat-clean-after-regenerate-pr)

You are a genius, how did you find such a rare bug

**Comment by wtlyu** [comment]
> @wtlyu here is a video. sorry its short, using free service
> 
> https://gyazo.com/c3b49ae2cb348963898ee2e069398238
> 
> im sure to be on your latest branch [feat-clean-after-regenerate-pr](https://github.com/wtlyu/chatgpt-clone/tree/feat-clean-after-regenerate-pr)

seems fixed, confirm?

**Comment by wtlyu** [comment]
reason:

isSubmitting is set to true when submiting new message.
in useEffect(xxx, [submission]), it will set isSubmitting to false when submission changes.

So that if submission is set to a new value, isSubmitting becomes true then false. -> stop generating disappears.

**Comment by danny-avila** [comment]
@wtlyu you are the genius here, I’m still wrapping my head around the branching.

I promise to clean up to accommodate your logic soon

I need to take a break for a bit but will check soon

@revolverinegirl https://discord.gg/RYFcYbmm very minimal for now haha

**Comment by wtlyu** [comment]
@danny-avila I will go sleep now. it's your turn hhh.

**Comment by wtlyu** [comment]
well , that line is added in your commit `fix: mobile styling after regen buttons`. (dont worry, I'm just a little bit curious why this bug not discovered before)
maybe that's a typo.

**Comment by danny-avila** [comment]
> well , that line is added in your commit `fix: mobile styling after regen buttons`. (dont worry, I'm just a little bit curious why this bug not discovered before) maybe that's a typo.

which line? I don't remember if i noticed it before

Looks like this is pretty good for merging now, great work. the only thing is the stopped message not saving, but i can maybe get to this this weekend. Also there is weird behavior when you 'play' with the branching/regen/stopping simultaneously, but that is an edge case of toying with the system, i will document the experience better at some point.

I'm going to start my sprint in a few hours. very happy with the progress so far, searching is going to be a game changer and have most of the logic done already.

**Comment by wtlyu** [comment]
saving the cancelled message in db is clear

save the message with text and correct parentmessageid, make sure it has a messageId (ok to be fake). then add field cancel =true. thats all

another thing can do is add a notify of the cancelled message in ui. for exampld a yellow box？

**Comment by wtlyu** [comment]
https://user-images.githubusercontent.com/8267138/225997631-5e6f61dc-a2d1-4ccc-94a1-5261957b521d.mp4

FYI
also fix these UI bug in mobile. but changes are a little big.

**Comment by danny-avila** [comment]
are you saying the bug is present and needs fixed with the UI being 'bouncy' ? seems like this is it? https://stackoverflow.com/a/74189866

I don't have very much experience with mobile styling so this is new to me

**Pull request merged**
