### PR TITLE
Use npm ci rather than install to be consistent with lock file

### PR DESCRIPTION
**Pull request by HyunggyuJang**
Otherwise, lock file is just ignored.

### CODE REVIEW

**Review by danny-avila — APPROVED** [review]

**Comment by danny-avila** [comment]
I'm just now getting to this, and I know this is backwards testing post-merge, but my docker build is now taking minutes (possibly stuck?) as opposed to less than a minute from before

**Comment by HyunggyuJang** [comment]
> I'm just now getting to this, and I know this is backwards testing post-merge, but my docker build is now taking minutes (possibly stuck?) as opposed to less than a minute from before

Have you updated your lock files before building it?

**Comment by danny-avila** [comment]
i ran a clean install locally that's all

**Comment by danny-avila** [comment]
It might be unrelated, npm install doesn't seem to be working either. could be my local network issue

**Comment by HyunggyuJang** [comment]
> It might be unrelated, npm install doesn't seem to be working either. could be my local network issue
Got it! Thanks for your elaboration. Please let me know if there is any problem!

**Pull request merged**
