### PR TITLE
Remove crypto.randomUUID() from client side

### PR DESCRIPTION
**Pull request by HyunggyuJang**
Unless, if we tries to access the client side page from http protocol, crypto.randomUUID() isn't available.

### CODE REVIEW

**Comment by wtlyu** [comment]
I got your idea. but it's not safe to use hardcoded messageId. mesaageId should never be duplicated, in any cases. do we have another random way to generate uuid-like messageId?

**Comment by wtlyu** [comment]
Update. it's not limited to be a uuid. any string that not duplicated is acceptable

**Comment by wtlyu** [comment]
> crypto.randomUUID() is now standard on all modern browsers and JS runtimes. However, because new browser APIs are restricted to secure contexts, this method is only available to pages served locally (localhost or 127.0.0.1) or over HTTPS.
> 
> For readers interested in other UUID versions, generating UUIDs on legacy platforms or in non-secure contexts, there is the uuid module. It is well-tested and supported

from Google. that would be a better choice

**Comment by wtlyu** [comment]
https://www.npmjs.com/package/uuid

seems to be a replace choice. to strictly avoid duplicated id, we can add timestamp to the uuid string.

**Comment by HyunggyuJang** [comment]
> https://www.npmjs.com/package/uuid
> 
> seems to be a replace choice. to strictly avoid duplicated id, we can add timestamp to the uuid string.

LGTM! I'll do that in a minute. Thanks for your elaboration!

**Comment by HyunggyuJang** [comment]
@wtlyu I gone with 
```javascript
crypto.getRandomValues(new Uint8Array(1))[0] + Date.now()
```
Will it be sufficient?

**Comment by wtlyu** [comment]
looks good. do you test it？

**Comment by HyunggyuJang** [comment]
Yes it works fine in my env!

**Review by danny-avila — APPROVED** [review]

**Pull request merged**
