### PR TITLE
🔍 feat: Filter MultiSelect and SelectDropDown (+variants) + CSS fixes for Scrollbar

### LINKED ISSUE #1815: Enhancement: Searchable Dropdown for Model list
### Discussed in https://github.com/danny-avila/LibreChat/discussions/1813

<div type='discussions-op-text'>

<sup>Originally posted by **peterhoang** February 16, 2024</sup>
This would be a nice QoL improvement for users of Openrouter.ai, like myself. 

I attempted this myself with https://ariakit.org/examples/combobox-radix-select but was unable to get it working nicely with the exsiting code base--I'm not familiar with its inner workings.</div>

### PR DESCRIPTION
**Pull request by f1yn**
> Some of the components that this rolls out to might be used in ways I can't predict well in this PR. I made the code easy enough that we can account for this, but someone with more understanding of the different pages selects are used might want to chime in. Tests are passing at least.

## Summary

- Added MultiSeach component, which enables search-based filtering in multi element list components (resolves #1815)
- Rolled out said component into various select based views
- Fixed issue reported on [Discord](https://discord.com/channels/1086345563026489514/1105648303909126144/1217490193251176518) related to scroll-bar not appearing correctly on Chrome browsers

**minor**
- Updated build file to not enforce minification during development builds
- Minor type updates, Noticed that the `cn` helper wasn't accounting for the boolean states, so I corrected this.

prefinal-list
prefinal-setting-list-example
prefinal-unfocused-list

## Change Type

Please delete any irrelevant options.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Translation update

## Testing

In various views that use Select lists with more than 10 items, a search bar appears.

## Checklist

Please delete any irrelevant options.

- [x] My code adheres to this project's style guidelines (I think so?)
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] My changes do not introduce new warnings
- [x] Local unit tests pass with my changes (`npm run test` passes in the `client` directory)

### CODE REVIEW

**Comment by danny-avila** [comment]
Thank you for your work on this!

 I think when elements exceed 10 is great and along the lines what I was envisioning. Another approach could be % of viewport the items take but this is fine.

for styling, I would make the search icon slightly smaller but I'm happy to merge as-is and adjust later.

Just curious, when did you find the need to make minification options explicit? I wasn't experiencing difficulties with minified code in dev, or does that just avoid minification altogether in dev mode? I suppose the code was still being minified but sourcemapped in dev mode.

**Comment by f1yn** [comment]
Hey @danny-avila, I think it would be safe to remove this. I was experiencing issues in react dev tools, but it was because I accidentally used the static build proxy that's provided by the api on port:3080.

The better solution in this case would to be to disable the static proxy on the backend when dev mode is enabled - which is not what I ended up doing. I'll amend the PR to make sure that config file gets reverted.

**Comment by f1yn** [comment]
@danny-avila - just updated and removed those vite changes 👍🏻

**Comment by danny-avila** [comment]
Thanks, going to test this today.

**Comment by danny-avila** [comment]
Made some edits on this, closing in favor of https://github.com/danny-avila/LibreChat/pull/2138

**Pull request closed without merging**
