### PR TITLE
⚡ feat: Static File Caching

### PR DESCRIPTION
**Pull request by mawburn**
## Summary

Related documentation PR: https://github.com/LibreChat-AI/librechat.ai/pull/95

This pull request introduces static file caching and Gzip compression to the project, significantly enhancing its performance and efficiency. By implementing static file caching, we enable frequently accessed files like images, CSS, and JavaScript to be stored locally on the user's device, reducing the need for repeated server requests and decreasing load times. This is only triggered when `NODE_ENV` is set to `production`.

[MDN Cache-Control](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#response_directives)

Additionally, the inclusion of [compression](https://github.com/expressjs/compression) reduces the size of these files before transmission, minimizing bandwidth usage and further speeding up page load times. Combined with the `Cache-Control` headers this should be a very negligible load on the server. 

These optimizations collectively lead to a faster, more responsive user experience, lower server load, and improved scalability, making the application more robust and user-friendly. 

On my instance here are the results:

**Using compression → 2.4mb transferred, from 6.2mb total**
Screenshot 2024-07-26 at 11 03 08 AM

**Using compression + local caching on a refresh → 664kb transferred, from 6.2mb total**
Screenshot 2024-07-26 at 11 04 34 AM (1)

With out these, the full 6.2mb was transferred on page load/refresh or were getting 304 responses from the API, causing extra load on the API server that isn't needed.

**Update:**

I have this deployed in our production for thousands of users and it seems to have also fixed our issues with memory usage. 

This is with 8gb of memory and it was using 70-85% memory all the time. Where now it's about 15-18%. 

Screenshot 2024-07-29 at 12 08 20 PM (1) (1)

## Change Type

- [x] New feature (non-breaking change which adds functionality)

## Checklist

Please delete any irrelevant options.

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have made pertinent documentation changes

## Copilot Summary

This pull request includes several changes to enhance the server's performance and improve caching mechanisms. The most important changes include adding the `compression` middleware, implementing a static file cache control utility, and updating the relevant configurations and routes.

### Performance Improvements:

* [`api/package.json`](diffhunk://#diff-d0ab9c1cc78fba971b5270314ad877706d340d099b42f46a406fc5de6a32fdf0R48): Added the `compression` package to enable response compression.
* [`api/server/index.js`](diffhunk://#diff-a7e858ecd8004b310ac59b25e999ad677fba3cd712ab7f7da4f0aa5bf8d28cf4R7): Integrated the `compression` middleware to compress response bodies for all requests. [[1]](diffhunk://#diff-a7e858ecd8004b310ac59b25e999ad677fba3cd712ab7f7da4f0aa5bf8d28cf4R7) [[2]](diffhunk://#diff-a7e858ecd8004b310ac59b25e999ad677fba3cd712ab7f7da4f0aa5bf8d28cf4R43-R51)

### Cache Control Enhancements:

* [`.env.example`](diffhunk://#diff-a3046da0d15a27e89f2afe639b25748a7ad4d9290af3e7b1b6c1a5533c8f0a8cR414-R422): Added configuration options for static file cache control, including `STATIC_CACHE_MAX_AGE` and `STATIC_CACHE_S_MAX_AGE`.
* [`api/server/utils/staticCache.js`](diffhunk://#diff-3d5d3f8283b1418eb0460f7a42e9497abb4bde4d0b72de3e81ba6c6bff41ec56R1-R21): Created a new utility to handle static file caching with configurable cache headers based on environment variables.
* [`api/server/index.js`](diffhunk://#diff-a7e858ecd8004b310ac59b25e999ad677fba3cd712ab7f7da4f0aa5bf8d28cf4R21): Replaced `express.static` with the new `staticCache` utility for serving static files. [[1]](diffhunk://#diff-a7e858ecd8004b310ac59b25e999ad677fba3cd712ab7f7da4f0aa5bf8d28cf4R21) [[2]](diffhunk://#diff-a7e858ecd8004b310ac59b25e999ad677fba3cd712ab7f7da4f0aa5bf8d28cf4R43-R51)
* [`api/server/routes/static.js`](diffhunk://#diff-ad81b38abfe1e981ba68498893194602759fdb2cdbb2d07c44362f6fe49c3addR2-R6): Updated the static routes to use the new `staticCache` utility.

### CODE REVIEW

**Comment by lidonius1122** [comment]
I see a potential issue with the compression implementation. For users like me who use Traefik with Brotli or Zstd compression, having Gzip at the application level prevents these more efficient methods from being applied.

It would be better if we had something like a `DISABLE_COMPRESSION` environment variable. This way, users could choose to handle compression at the reverse proxy level if needed.

**Comment by mawburn** [comment]
That's a good point @lidonius1122, I can add that.

**Comment by danny-avila** [comment]
thanks!

**Comment by mawburn** [comment]
Done @lidonius1122

**Comment by lidonius1122** [comment]
Seems to be working as it should so far @mawburn

**Review by danny-avila — APPROVED** [review]

**Comment by danny-avila** [comment]
> I see a potential issue with the compression implementation. For users like me who use Traefik with Brotli or Zstd compression, having Gzip at the application level prevents these more efficient methods from being applied.
> 
> It would be better if we had something like a `DISABLE_COMPRESSION` environment variable. This way, users could choose to handle compression at the reverse proxy level if needed.

I've added notes in docs to mention this

https://github.com/LibreChat-AI/librechat.ai/pull/98

**Pull request merged**
