### PR TITLE
feat: CI Docker builds for arm64v8

### PR DESCRIPTION
**Pull request by fidoriel**
# Pull Request Template
## Summary

Build ghcr.io images for armv8 like in https://github.com/danny-avila/LibreChat/issues/1134 suggested. To not have to build LibreChat on Raspberry Pi (64bit). Very old Models are not covered (but can be added easily).

Therefor this PR utilizes the Canonical qemu/buildx/meta/build actions to build, tag and push the images. This will produce a multi arch manifest for docker, so that the images will be easy to use with both amd64 and arm64v8. 

## Change Type

Please delete any irrelevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation update
- [ ] Translation update

## Testing

Testing is a little bit difficult, if I find time I will test on my fork.

## Checklist

- [ ] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [ ] I have commented in any complex areas of my code
- [ ] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [ ] I have written tests demonstrating that my changes are effective or that my feature works
- [ ] Local unit tests pass with my changes
- [ ] Any changes dependent on mine have been merged and published in downstream modules.

### CODE REVIEW

**Comment by danny-avila** [comment]
Thanks! I may have to use ACT to test this properly, or how are you testing it?

https://github.com/nektos/act

**Comment by fidoriel** [comment]
I think act does not support docker in docker. Or do they now? Last time I checked, they did not but wanted to add support. I have tested it on my fork. See CI run: https://github.com/fidoriel/LibreChat/actions/runs/7601168119

Here is the result: https://github.com/fidoriel/LibreChat/pkgs/container/librechat
I have violated semver on my release, so I will release again ^^

**Comment by pocketken** [comment]
FWIW, we're running LibreChat in AKS on ARM nodes (`Standard_D4ps_v5`) building locally with more or less the same changes and it is working great.  @fidoriel beat me to the punch in opening a PR.

**Review by danny-avila — APPROVED** [review]

**Comment by danny-avila** [comment]
Thanks again. Just realized probably the same changes need to be made to `.github/workflows/dev-images.yml` ?

**Pull request merged**
