### PR TITLE
Feature: New Prompt Library Page

### PR DESCRIPTION
**Pull request by walbercardoso**
## Summary

A page containing pre-defined prompts made by the LibreChat community. This is a feature based on Clara's PR, where I made adjustments to the code and improved interactions with the preset option. Added a button to the main chat page to access the Prompt Library. This button is only visible with the bingAI and openAI models. When starting a conversation, the buttons and options for selecting models will be invisible, simulating what happens with ChatGPT.

Visible only at OpenAI and BingAI
image

image

Hide Model selection and buttons after conversation starts
image

## Change Type

Please delete any irrelevant options.

- [x] New feature (non-breaking change which adds functionality)
- [x] Translation components available on Eng and Br

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.

### CODE REVIEW

**Comment by walbercardoso** [comment]
Got error at crypto.js when i try to run npm run test:api

FAIL  server/routes/__tests__/config.spec.js
  ● Test suite failed to run

    TypeError: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined

      1 | const crypto = require('crypto');
    > 2 | const key = Buffer.from(process.env.CREDS_KEY, 'hex');
        |                    ^
      3 | const iv = Buffer.from(process.env.CREDS_IV, 'hex');
      4 | const algorithm = 'aes-256-cbc';
      5 |

      at Object.from (server/utils/crypto.js:2:20)
      at Object.require (server/utils/index.js:5:21)
      at Object.require (server/routes/ask/openAI.js:4:43)
      at Object.require (server/routes/ask/index.js:3:16)
      at Object.<anonymous> (server/routes/index.js:1:29)
      at Object.require (server/routes/__tests__/config.spec.js:3:16)

**Comment by danny-avila** [comment]
Hi @walbercardoso thanks for your PR. I would like you to invite me to your fork as a collaborator as I need to address a couple of things here.

This is largely my fault, but we are remiss to use axios/native fetch api calls and combine them with recoil, when we can exclusively benefit from react query especially in this case. I'm working little by little to refactor this in other areas of the app, like here https://github.com/danny-avila/LibreChat/pull/1085, but I can take over to write this out in your branch

Also I want to explore some other way of packaging the pre-made presets/prompts.. I'm still thinking about this but I would like to avoid adding 80+ files

**Comment by danny-avila** [comment]
Also due to the timing, this won't make it to 0.6.0 but will make to the 0.6.1 release

**Comment by fuegovic** [comment]
> Also I want to explore some other way of packaging the pre-made presets/prompts.. I'm still thinking about this but I would like to avoid adding 80+ files

over time, we probably have collected over 4000 prompt presets in the `#presets` channel 😬

**Comment by walbercardoso** [comment]
hi @danny-avila thanks for your reply. I understand your concern. So I think we can try a different approach. What do you think about replacing the Import Preset option for this prompt library. This way, at first it would be empty and as the user imports his preset or saves a preset he wants, the library will be populated?

**Comment by walbercardoso** [comment]
I also invited you as collaborator.

**Comment by walbercardoso** [comment]
Also replaced axios as you asked me :)

**Comment by walbercardoso** [comment]
> > Also I want to explore some other way of packaging the pre-made presets/prompts.. I'm still thinking about this but I would like to avoid adding 80+ files
> 
> over time, we probably have collected over 4000 prompt presets in the `#presets` channel 😬

I know. But i only get some. But we can do as i mentioned before. Populate that as the user imports their own preset

**Comment by walbercardoso** [comment]
Empty library by default.
image

When the user imports the preset file
image

**Comment by fuegovic** [comment]
Quick question, does the import function supports importing multiple files at once?

**Comment by walbercardoso** [comment]
> Quick question, does the import function supports importing multiple files at once?

As I am using the same existing component, it does not allow more than 1 file at a time. You would have to change the FileUpload logic

**Comment by walbercardoso** [comment]
I created a new component so I didn't have to change FileUpload.

Multiples files upload:
image

image

**Comment by walbercardoso** [comment]
Cant figure it out why test:api still not passing tests

**Comment by frankhommers** [comment]
Same thing as my FR https://github.com/danny-avila/LibreChat/issues/1016

**Comment by danny-avila** [comment]
> Same thing as my FR #1016

Hi Frank, this is not the same your request, which I understood to mean Prompt Variables. I'm planning on integrating that whether or not it's part of this specific PR, but currently I don't believe it is. I believe Prompt Variables should definitely be added

**Comment by fuegovic** [comment]
@danny-avila, @Berry-13  
Maybe one one you two could check it out when you have a minute, as far as I know this is functionnal but there's a problem with the tests failing that @walbercardoso couldn't figure out.

**Pull request closed without merging**
