### PR TITLE
Uplift chatgpt-api version

### PR DESCRIPTION
**Pull request by HyunggyuJang**
Sydney is back :)

### CODE REVIEW

**Comment by danny-avila** [comment]
Sweet! Are you still working on this? it's marked as a draft

**Comment by HyunggyuJang** [comment]
> Sweet! Are you still working on this? it's marked as a draft
Yes, currently, the message tree for bingai and sydney is mangled. I fixed for Sydney, and will work on bingai tmr!

**Comment by danny-avila** [comment]
Thank you!

**Comment by HyunggyuJang** [comment]
@danny-avila Can you check?

**Review by danny-avila — APPROVED** [review]

**Comment by danny-avila** [comment]
I merged this, but this issue had been happening even before that: currently, I'm trying to debug the latest changes to the master branch as chatgpt is not retaining conversations. I'm not very familiar with how the conversation handling has evolved since I first designed it, so I may limit backend changes until there's a proper test env. 

Rolling back the node-chatgpt-api version didn't fix the issue. Luckily, my search branch is fully functional, and I may end up using it as the main branch and manually walking back the latest commits made to master.

**Comment by danny-avila** [comment]
Did my comb-through, I did identify the api update may have been part of the issue but unsure, had a lot more housekeeping to do.

@HyunggyuJang would you mind trying again off the latest master branch? you can test the latest api using the alias i installed 

    "chatgpt-latest": "npm:@waylaidwanderer/chatgpt-api@^1.31.6",
    
 so you'll need to change

`const { BingAIClient } = (await import('@waylaidwanderer/chatgpt-api'));`

and sydney to `await import('chatgpt-latest')` 

Thank you!

**Comment by HyunggyuJang** [comment]
> Did my comb-through, I did identify the api update may have been part of the issue but unsure, had a lot more housekeeping to do.
> 
> @HyunggyuJang would you mind trying again off the latest master branch? you can test the latest api using the alias i installed
> 
> ```
> "chatgpt-latest": "npm:@waylaidwanderer/chatgpt-api@^1.31.6",
> ```
> 
> so you'll need to change
> 
> `const { BingAIClient } = (await import('@waylaidwanderer/chatgpt-api'));`
> 
> and sydney to `await import('chatgpt-latest')`
> 
> Thank you!

Got it! Will work on that.

**Comment by danny-avila** [comment]
Thank you! last thing, work off 'working-branch' since master is giving me issues. it's difficult to debug because it may be due to auto merging

**Comment by danny-avila** [comment]
@HyunggyuJang as far as testing goes, you can just focus on reproducing your changes for bing/sydney with the alias package, and then i can go from there!

**Comment by danny-avila** [comment]
FYI I reproduced your changes with some minor tweaks and got this working alongside the old chatgpt-api version as still debugging changes there

**Pull request merged**
