### PR TITLE
🅰️ feat: dynamic font size

### PR DESCRIPTION
**Pull request by krakenftw**
Introduced font-sizing in settings with all translations, Added a CSS var for font-size which changes according to the localstored font-size or default i.e 16px. #3207 

# Pull Request Template

⚠️ Before Submitting a PR, Please Review:
- Please ensure that you have thoroughly read and understood the [Contributing Docs](https://github.com/danny-avila/LibreChat/blob/main/.github/CONTRIBUTING.md) before submitting your Pull Request.

⚠️ Documentation Updates Notice:
- Kindly note that documentation updates are managed in this repository: [librechat.ai](https://github.com/LibreChat-AI/librechat.ai)

## Summary

Please provide a brief summary of your changes and the related issue. Include any motivation and context that is relevant to your changes. If there are any dependencies necessary for your changes, please list them here.

## Change Type

Please delete any irrelevant options.

- [x] New feature (non-breaking change which adds functionality)

## Testing

Please describe your test process and include instructions so that we can reproduce your test. If there are any important variables for your testing configuration, list them here.

## Checklist

Please delete any irrelevant options.

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] My changes do not introduce new warnings
- [ ] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [ ] Any changes dependent on mine have been merged and published in downstream modules.
- [ ] A pull request for updating the documentation has been submitted.

### CODE REVIEW

**Comment by krakenftw** [comment]
also i am fairly new to open source, please point out the points of improvement. Here to learn : )

**Comment by danny-avila** [comment]
Hi @krakenftw thanks for your contribution.

At the moment, I can't accept this PR, there are too many linting changes in the stylesheet for me to review. In general, you should prevent any linters that don't result in git differences. If you would like to contribute a CSS linter setup, that would be in a separate PR.

Also, I think it makes sense to make the font size configurable for messages exclusively.

Your addition to the settings tab is still useful, and I can take over from here to revise this if you'd like.

**Comment by krakenftw** [comment]
Hey @danny-avila
The linting changes were mess for me honestly, Prettier was doing the stuff and changed the whole thing.
So basically that font-size would only affect the user/model messages?. I am ready to do this.
Also an idea of which method i should opt to do this would be helpful. Since i am fairly new to open source.

**Comment by danny-avila** [comment]
Sorry for the long wait, applying my changes here: https://github.com/danny-avila/LibreChat/compare/feat/dynamic-font-size?expand=1

**Pull request closed without merging**
