### PR TITLE
✨ feat: Assistants API, General File Support, Side Panel, File Explorer

### PR DESCRIPTION
**Pull request by danny-avila**
## Summary

I was hoping to finish today but there are still some things left to polish I should wrap up in the next couple of days.

A full write up of the changes will also be in order (WIP).

However, those who are willing to try this update can check out the branch. 

Use it knowing that it is still incomplete and things may change still.

### Tasks needed to merge

- [x] Merge necessary open Pull Requests and fixes
- [x] General UI/UX: 
	- [x] Retrieval Tool Call polish
	- [x] Action Tool Call polish
- [x] Side panel optimization
	- [x] mobile optimization
	- [x] save collapsed/visible state of side panel
	- [x] setting to completely hide panel (for admin and client)
	    - [x] for admin
	    - [x] for client
- [x] Preset Settings
	- [x] Additional instructions
	- [x] model
- [x] Files:
	- [x] `context/origin` field in file schema
	- [x] file upload rate limiting
	- [x] Configurable file limits
	- [x] Allow disabling file uploads completely
- [x] Handle Assistant Errors during chat and sync up thread messages
- [ ] Localization of new messages

### Stretch Goals

_Items I will attempt to finish by end of week but may still merge without them_

- Append Messages (1st priority stretch goal)
- Track Token Usage (must rely on API as token injection cannot be accounted)
- Conversation Starters
- Actions (already implemented but lacking OAuth and remote fetching specs)
	- fetch_openapi route
	- [x] authentication handling
		- [x] API key
		- OAuth

### Planned Updates to Assistants:

- Vision for Assistants
- make actions shareable between assistants (explicit option)
- make assistants shareable
- Functions (mirroring behavior of OpenAI playground)
- Tool feature to allow user input
- Configure Tool inputs/settings for the LLM to have pre-configured
- Image generation of assistant avatar (last priority stretch goal)
- limit assistant features (part of large role-based access controls update)

## Change Type

- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by miraeder** [comment]
Does this Assistants API functionality also cover Azure's new Assistant API? See [here](https://learn.microsoft.com/en-us/azure/ai-services/openai/assistants-quickstart?tabs=command-line&pivots=programming-language-studio)

**Comment by danny-avila** [comment]
> Does this Assistants API functionality also cover Azure's new Assistant API? See [here](https://learn.microsoft.com/en-us/azure/ai-services/openai/assistants-quickstart?tabs=command-line&pivots=programming-language-studio)

Azure’s assistant api just came out yesterday. It won’t be supported initially but just after this release I will work on it.

**Comment by danny-avila** [comment]
@miraeder it was easy enough to restrict certain assistant Ids that I will be including it in the release! See https://github.com/danny-avila/LibreChat/pull/1696/commits/b4aa1f22e93b7f57665f6bdcffc66f58c9c00cac

**Comment by grexzen** [comment]
You are amazing!

**Pull request merged**
