### PR TITLE
📖 docs: Update `multilingual_information.md`

### PR DESCRIPTION
**Pull request by jo-s-eph**
## Summary

Some minor grammatical errors in the French translation

## Change Type

Please delete any irrelevant options.

- [x] Documentation update
- [x] Translation update

## Testing
Doc enhancement, does not affect code operation.

## Checklist

- [ ] My code adheres to this project's style guidelines
- [ ] I have performed a self-review of my own code
- [ ] I have commented in any complex areas of my code
- [ ] I have made pertinent documentation changes
- [ ] My changes do not introduce new warnings
- [ ] I have written tests demonstrating that my changes are effective or that my feature works
- [ ] Local unit tests pass with my changes
- [ ] Any changes dependent on mine have been merged and published in downstream modules.

### CODE REVIEW

**Review by fuegovic — COMMENTED** [review]
Merci, le "ce" manquant (dans "ce projet") est en effet dû à une erreur d’inattention. Par contre je crois que “traduction” (au singulier) est la forme la plus courante lorsque l’on parle d’outils comme `Google Traduction`.

---

Thank you, the missing "ce" (in "ce projet") is indeed due to a lack of attention, however I believe that “translation” (in the singular form) is the most common form when we talk about tools like `Google Translate`.

image


image

image

**Comment by jo-s-eph** [comment]
Yeah my bad, just updated the commit

**Review by fuegovic — APPROVED** [review]

**Comment by fuegovic** [comment]
> Yeah my bad, just updated the commit

Thanks!

**Comment by danny-avila** [comment]
thanks!

**Pull request merged**
