### PR TITLE
ChatGPT UI Improvements

### PR DESCRIPTION
**Pull request by techwithanirudh**
## Summary

This pull request includes several enhancements to match the UI to OpenAI's ChatGPT.

### Chat Input
Before:
image

After:
image

Before:
image

After:
image

### Top Nav Menu

Before:
image

After:
image

(The mobile changes for this change were not added, instead the style reverts back to the original mobile position) (like the official ChatGPT)

### Messages

Before:
image

After:
image

Before:
image

After:
image

### Edit Message

Before:
image

After:
image

Before:
image

After:
image

### Archive Button
Before:
image

After:
image

Before:
image

After:
image

## Change Type

- [x] New feature (non-breaking change which adds functionality)

## Testing

N/A

### **Test Configuration**:

N/A

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] My changes do not introduce new warnings
- [x] Local unit tests pass with my changes

### CODE REVIEW

**Comment by techwithanirudh** [comment]
@danny-avila Could you please review this P.R?

**Comment by danny-avila** [comment]
Please make each change its own PR. Also please review the styling on mobile. The before/after screenshots should include this as well.

**Comment by techwithanirudh** [comment]
> Please make each change its own PR. Also please review the styling on mobile. The before/after screenshots should include this as well.

@danny-avila I split the P.R into multiple P.Rs and added screenshots for mobile devices.

**Comment by danny-avila** [comment]
> > Please make each change its own PR. Also please review the styling on mobile. The before/after screenshots should include this as well.
> 
> @danny-avila I split the P.R into multiple P.Rs and added screenshots for mobile devices.

thank you 🙏

**Pull request closed without merging**
