### PR TITLE
🚆 docs: Add Sealos 1-Click Deployment

### PR DESCRIPTION
**Pull request by yangchuansheng**
Add deploy on [Sealos](https://github.com/labring/sealos)

# Pull Request Template

## Summary

Please provide a brief summary of your changes and the related issue. Include any motivation and context that is relevant to your changes. If there are any dependencies necessary for your changes, please list them here.

## Change Type

Please delete any irrelevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [x] Documentation update
- [ ] Translation update

## Testing

Please describe your test process and include instructions so that we can reproduce your test. If there are any important variables for your testing configuration, list them here.

## Checklist

- [ ] My code adheres to this project's style guidelines
- [ ] I have performed a self-review of my own code
- [ ] I have commented in any complex areas of my code
- [ ] I have made pertinent documentation changes
- [ ] My changes do not introduce new warnings
- [ ] I have written tests demonstrating that my changes are effective or that my feature works
- [ ] Local unit tests pass with my changes
- [ ] Any changes dependent on mine have been merged and published in downstream modules.

### CODE REVIEW

**Comment by danny-avila** [comment]
thanks for this! I've never heard of this service, and I have a language barrier accessing it. Can you give a live deployed example?

**Comment by yangchuansheng** [comment]
> thanks for this! I've never heard of this service, and I have a language barrier accessing it. Can you give a live deployed example?

Thank you for your response! To help you get a better understanding, I will show you a live example of this service.

1️⃣ First, Click the following prebuilt template:


<p align="center">
  <a href="https://template.cloud.sealos.io/deploy?templateName=librechat">
    Deploy on Sealos
  </a>
</p>

if you have openai reverse proxy, replace the value of `OPENAI_REVERSE_PROXY`:



2️⃣ Click "Deploy on Sealos" on the template page to heading to [Sealos Cloud](https://cloud.sealos.io), then Sign in to Sealos Cloud.

3️⃣ After sign in, Sealos Clud will auto open "Template" App and head to LibreChat template.

4️⃣ Click "Deploy Application" on the template page to start deployment.

5️⃣ Once deployment concludes, click "Details" to navigate to the librechat application's details.



6️⃣ Wait for the application's status to switch to running. Subsequently, click on the external link to open the application's Web interface directly through the external domain.



Here is a live deployed example: https://librechat-pvtffxuv.cloud.sealos.io

Thanks!

**Comment by fanux** [comment]
@danny-avila [Sealos](https://github.com/labring/sealos)   is also a well-known open-source project that can start all dependencies of an application, including the database, with just one click. It is very convenient. You can also try clicking the one-click installation button to get LibreChat up and running in a few minutes. Sealos currently has nearly 100,000 registered users and is one of the largest container hosting platforms in China.

**Comment by danny-avila** [comment]
> @danny-avila [Sealos](https://github.com/labring/sealos) is also a well-known open-source project that can start all dependencies of an application, including the database, with just one click. It is very convenient. You can also try clicking the one-click installation button to get LibreChat up and running in a few minutes. Sealos currently has nearly 100,000 registered users and is one of the largest container hosting platforms in China.

Amazing thank you

**Comment by danny-avila** [comment]
@yangchuansheng Thank you very much for the instructions! Going to merge this and may I ask that you add this to the Deployment docs in another PR? You can simply add a new file under the deployment directory `docs/deployment`

**Review by danny-avila — APPROVED** [review]

**Comment by yangchuansheng** [comment]
> @yangchuansheng Thank you very much for the instructions! Going to merge this and may I ask that you add this to the Deployment docs in another PR? You can simply add a new file under the deployment directory `docs/deployment`

Absolutely, I'd be happy to add this to the Deployment documentation.

**Pull request merged**
