### PR TITLE
🛅 fix: Login/Registration Dynamic page titles based on `APP_TITLE`

### LINKED ISSUE #2702: [Bug]: App_TITLE is not applied at the Login Screen
### What happened?

I have changed the App Title but the Website Title on the Login Page stays LibreChat. 
After Login the name from .env is applied.

### Steps to Reproduce

1. change APP_TITLE in .env
2. build/run app

### What browsers are you seeing the problem on?

Chrome, Safari, Microsoft Edge

### Relevant log output

_No response_

### Screenshots

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by danny-avila**
Related to #2702

Updates the website title on the Login and Registration pages to match the `APP_TITLE` from `.env` configuration.

- Adds a `useEffect` hook in both `Login.tsx` and `Registration.tsx` components to dynamically set the document title to the `appTitle` obtained from `startupConfig`. This ensures that the website title on these pages reflects the current `APP_TITLE` setting from `.env`.
- Utilizes a fallback title 'LibreChat' in case `appTitle` is not available in the `startupConfig`, maintaining a default behavior.

---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/danny-avila/LibreChat/issues/2702?shareId=c1d6533e-4706-45a3-a9cf-560656fbc810).

### CODE REVIEW

**Comment by mkagit** [comment]
Danny, never merged?

**Comment by danny-avila** [comment]
> Danny, never merged?

This was me testing copilot workspaces. Check https://github.com/danny-avila/LibreChat/pull/2716

**Comment by mkagit** [comment]
I see but the issue with the website title Login and Registration not following the .env APP_TITLE is still there.

**Comment by markvshaney** [comment]
i unsubsribed months ago but i'm still getting spammed every five minutes-- is there any way you can do it from your end?  Thanks! good luck with your project

**Pull request closed without merging**
