### PR TITLE
Feat usersys

### PR DESCRIPTION
**Pull request by wtlyu**
This PR give a sample user system implementation.

It provide a new env config to enabled the user system, default to disabled
It provide a basic structure of login and logout.
Data is segregated by username
It provide a sample implementation of the login and logout logic. 

**It is not a production level code, It's just a sample for developer**

### CODE REVIEW

**Comment by wtlyu** [comment]
will, I'm sorry that I cannot submit this PR based on master, since it's tooooo far in my branch.

Actually it's only one commit based on feat-resubmit #55 :
[feat: add sample multi-user support](https://github.com/danny-avila/chatgpt-clone/pull/59/commits/b74cf6a6052ee6fc27112b57cca31fd3c8d7c840) 

Once the feat-resubmit is merged, I will rebase this brance and clean the commit

**Comment by DavesDevFails** [comment]
@wtlyu I've been looking at implementing users for a while but never got around to it... would love to give this a try.

**Comment by wtlyu** [comment]
will back to this once #55  finished

**Comment by wtlyu** [comment]
@danny-avila Code cleaned based on the latest master

**Comment by wtlyu** [comment]
Well I have to say I didn't get what's your concern. Maybe everything goes ok on my mac hhhh

**Pull request merged**
