### PR TITLE
docs: Utilize Meilisearch Using LibreChat in Render

### PR DESCRIPTION
**Pull request by itzraiss**
## Change Type

- [x] Documentation update

### CODE REVIEW

**Review by danny-avila — CHANGES_REQUESTED** [review]
Thanks for the PR! I think this docs update is in the wrong place though. I don't mind it being its own page but it should be under deployment, and it can also be part of the render page

https://docs.librechat.ai/deployment/render.html

You will also need to update mkdocs.yml located in the root of the project if you are adding a new page

**Comment by fuegovic** [comment]
> You will also need to update mkdocs.yml located in the root of the project if you are adding a new page

@itzraiss 
as well as the Table of Content in README.md

**Comment by itzraiss** [comment]
Right, all done!

**Review by danny-avila — APPROVED** [review]

**Comment by danny-avila** [comment]
Thanks!

**Pull request merged**
