### PR TITLE
feat: basic support mobile mode.

### PR DESCRIPTION
**Pull request by wtlyu**
including:
navbar show and hide,
similar fade animation,
auto close when select new convo,
mobile title will change with convo,
new chat button.

### CODE REVIEW

**Comment by wtlyu** [comment]
QQ20230312-004113 (1)

**Comment by wtlyu** [comment]
not sure if it match your expect. but I do really need mobile version🤣

**Comment by danny-avila** [comment]
This looks great! I understand, and I haven't gotten to it because mobile styling is not a priority for me. I would like to troubleshoot how the messages seem to re-render upon conversation. I noticed the edit user message button behaves differently on the official site with mobile styling, but I can get around to this when I add that functionality!

**Comment by wtlyu** [comment]
yep I agree. For me, make a work anyway is first thing to do, my pr is also not a 100% copy of official looking. but it work🤣

**Comment by danny-avila** [comment]
Thanks so much for your contributions!

**Pull request merged**
