### PR TITLE
refactor: Settings/Presets UI Restructure, convert many files to TS

### PR DESCRIPTION
**Pull request by danny-avila**
Addresses #739 as this is necessary for modularity of settings and makes it easier to integrate additional UI features and adding new endpoints. This will improve the DX greatly for adding new buttons to match the latest styling of chat.openai.com

This is a rough outline of the new structure, but basically follows a standard format now
```bash
EndpointSettings # (for Presets/MessageHeader)
    |___Settings # ( within Dialog, same components as below )
TextChat
    |___GenerationButtons # (where stop/continue/regenerate will live)
    |___OptionsBar # (previously, this component didn't exist and a version of it was repeated for each Endpoint)
               |___ModelSelect # ( endpoint specific buttons )
               |___Settings # ( within Popover, same components as above )
                      |___PopoverButtons

```

Converted almost all files touched to typescript and fixed several UI bugs as a result.

Took the opportunity to improve mobile/desktop UI for settings.

Dependency cycle imports were fixed and now correctly linted.

Fixed a bug with update script, as new `fs.rm` method is async and was causing issues. using old method now

Added update current branch feature to update script, and added npm command for rebuilding the package-lock file.

Styles Nav to match mobile styling with official site

Fixed node_module resolution with path mapping in ./client/tsconfig.json

Adds useLocalize hook to reduce boilerplate for using translations
```js
import { useLocalize } from '~/hooks';

function SomeComponent() {
  const localize = useLocalize();
  const translation = localize(text) // params: phraseKey: string, values?: string[]
```

Gradient is now less pronounced on desktop and non-existent in mobile views
before:
image

after:

image

### CODE REVIEW

**Review by techwithanirudh — COMMENTED** [review]
## Awesome P.R, but I found a few small issues

1. When you change the endpoint while having the settings panel open, e.g, switching from Plugins to ChatGPT Browser (which doesn't have a panel), it shows it blank, instead of closing:

Endpoint Change Issue

2. The model select for chatgpt-browser is a bit small, causing the text to get cut off:

Model Select Issue

3. The space taken from the options menu for each endpoint differs, resulting in inconsistency:

Options Menu Space Issue 1

Options Menu Space Issue 2

Options Menu Space Issue 3

4. The square endpoint button looks odd next to the rounded input:

Endpoint Button Style Issue

5. The 'Set token first' element is not aligned centered vertically and horizontally properly:

Alignment Issue

6. Clicking on the top bar for plugins won't bring the preset edit / config edit modal:

Top Bar Issue

7. Query: Won't adding a preset change / delete the plugin's support's system prompt?

Edit Preset

8. The spacing is different for the edit preset and the view options:

Spacing Issue 1

Spacing Issue 2

9. The icon for the send button needs to be changed to the official OpenAI one:

Send Button Icon Issue

10. In the mobile view, OpenAI adds an X Button to dismiss the sidebar, but Libre uses the same dismiss button as in the desktop view:

Libre Mobile View:
Libre Mobile View

ChatGPT Mobile View:
ChatGPT Mobile View

11. The logos of Libre and ChatGPT are not the same:

Libre Logo:
Libre Logo

ChatGPT Logo:
ChatGPT Logo

12. The OpenAI top bar and Libre bar look a bit different:

Libre Top Bar:
Libre Top Bar

OpenAI Top Bar:
OpenAI Top Bar

---

#### Suggested Changes:

1. Automatically close the settings panel when switching to an endpoint without a panel.
2. Enlarge the model selection area in chatgpt-browser to prevent text truncation.
3. Ensure consistent height for each endpoint settings.
4. Use a consistent button style (either all square or all rounded) throughout the interface.
5. Properly align the 'Set token first' element both vertically and horizontally.
6. Add support to open preset edit / config edit modal when clicking on the top bar for plugins.
7. Address the query about adding a preset and its impact on the plugin's support system prompt.
8. Adjust the spacing for edit preset and view options to match.
9. Update the send button icon to the official OpenAI logo.
11. Use OpenAI's dismiss button style for the mobile view.
12. Ensure the logos of Libre and ChatGPT are the same.
13. Harmonize the design of the top bar to match the OpenAI style for a unified appearance.

Thank you for considering these changes. Your attention to detail will greatly improve the user experience!

**Comment by danny-avila** [comment]
@techwithanirudh Thanks for your feedback

> 1. When you change the endpoint while having the settings panel open, e.g, switching from Plugins to ChatGPT Browser (which doesn't have a panel), it shows it blank, instead of closing:

done

> 2. The model select for chatgpt-browser is a bit small, causing the text to get cut off:

done

> 3. The space taken from the options menu for each endpoint differs, resulting in inconsistency:

fixed, note this only takes the full screen on a small phone (iphone SE) but maybe in the future it can be dynamic to mobile screen size

> 4. The square endpoint button looks odd next to the rounded input:

I mostly disagree, but I added a small padding view to make it look a bit better in mobile view

>5. The 'Set token first' element is not aligned centered vertically and horizontally properly:

This is a very small detail but I believe I improved it here: 
image


> 6. Clicking on the top bar for plugins won't bring the preset edit / config edit modal:

Fixed.

> 7. Query: Won't adding a preset change / delete the plugin's support's system prompt?

No, plugins are only activated when they are selected.

> 8. The spacing is different for the edit preset and the view options:

it's going to be a bit different with the inability to change endpoints and no preset name config, but i matched them a little better now

> #'s 9 - 12

Not relevant to this PR but I did more closely match the header to the official site. Contributions welcome

**Comment by techwithanirudh** [comment]
## Awesome P.R, but I have some more feedback

1. The clear button has a border, which kind of looks off, The border below the description of the modal should be even more below, and the clear button is a lil bit smalelr in width compared to cancel.



2. On smaller screens, `Use Functions` and `Skip Completion` overlap



3. When the theme is set to system, the input gradient turns to light, instead of the system mode being dark.



4. The top-bar in ChatGPT is kind-of sticky, but Libre's isn't



5. The heading, and the close button is not centered properly



6. For edit preset the scrollbar shouldn't be on the whole modal, it should be on the modal body,
Also, it should be like the save convo as preset and not overflow till the buttons area, instead stop at the buttons div 




7. This would be better if it were spaced between



---

#### Suggested Changes:


Thank you for considering these changes. Your attention to detail will greatly improve the user experience!

**Comment by danny-avila** [comment]
> ## Awesome P.R, but I have some more feedback
> 1. The clear button has a border, which kind of looks off. The border below the description of the modal should be even more below, and the clear button is a little bit smaller in width compared to cancel.
> 
> Clear Button Issue
> 
> 2. On smaller screens, `Use Functions` and `Skip Completion` overlap.
> 
> Overlap Issue
> 
> 3. When the theme is set to system, the input gradient turns light, instead of the system mode being dark.
> 
> Theme Issue
> 
> 4. The top-bar in ChatGPT is kind-of sticky, but Libre's isn't.
> 
> Top-bar Issue
> 
> 5. The heading and the close button are not centered properly.
> 
> Alignment Issue
> 
> 6. For edit preset, the scrollbar shouldn't be on the whole modal, it should be on the modal body. Also, it should be like the `Save Convo As A Preset` and not overflow till the buttons area, instead stop at the buttons div.
> 
> Scrollbar Issue
> 
> 7. This would be better if it were spaced between.
> 
> Spacing Issue
> 
> #### Suggested Changes:
> 1. Adjust the clear button's style to remove the border and ensure it has the same width as the cancel button.
> 2. Fix the overlapping issue of `Use Functions` and `Skip Completion` on smaller screens.
> 3. Ensure the input gradient remains dark when the theme is set to the system mode.
> 4. Make the top-bar in Libre sticky like the one in ChatGPT.
> 5. Center the heading and close button properly for a balanced appearance.
> 6. Modify the edit preset modal to have a scrollbar only in the modal body and stop it at the buttons div, following the style of the `Save Convo As A Preset` modal.
> 7. Add proper spacing to improve the visual appeal.
> 
> Thank you for considering these changes. Your attention to detail will greatly improve the user experience!

I’m working on the gradient issue, but that is all. You are welcome to make those changes in a PR

**Comment by danny-avila** [comment]
> ## Awesome P.R, but I have some more feedback
> 1. The clear button has a border, which kind of looks off. The border below the description of the modal should be even more below, and the clear button is a little bit smaller in width compared to cancel.
> 

done
 
> 2. On smaller screens, `Use Functions` and `Skip Completion` overlap.
> 

fixed

> 
> 3. When the theme is set to system, the input gradient turns light, instead of the system mode being dark.
> 

fixed

> 4. The top-bar in ChatGPT is kind-of sticky, but Libre's isn't.
> 

not planned/not done (PR welcome)

> 5. The heading and the close button are not centered properly.
> 

not true, and if true on your screen, not planned/not done (PR welcome)

image


> 6. For edit preset, the scrollbar shouldn't be on the whole modal, it should be on the modal body. Also, it should be like the `Save Convo As A Preset` and not overflow till the buttons area, instead stop at the buttons div.
> 

fixed

> 7. This would be better if it were spaced between.

fixed

> 8, Make the endpoint options take full width.

fixed

**Comment by danny-avila** [comment]
## Before PR:
image

## After:

**Pull request merged**
