### PR TITLE
Update .env.example

### PR DESCRIPTION
**Pull request by fuegovic**
I continued the work on the standardization of the layout. I eliminated duplicate key=value pairs to simplify the configuration and reduce the likelihood of errors. I also updated some of the commented instructions and notes throughout the file to keep the instructions clear while making it easier to prevent errors when using a script to parse the key=value pairs.

### CODE REVIEW

**Comment by danny-avila** [comment]
I think you removed some comments that allow tokens for Bing and ChatGPT Browser to be provided by user

```
# Set to "user_provided" to allow user provided token.
# BINGAI_TOKEN="user_provided"
```

Can you update the language for this? It applies to BINGAI_TOKEN and CHATGPT_TOKEN

**Comment by fuegovic** [comment]
Will put those back when I  have a minute. By the way what are those for, is it for the upcoming user system?

**Comment by fuegovic** [comment]
I fixed it in my latest commit

**Review by danny-avila — APPROVED** [review]

**Comment by danny-avila** [comment]
Thanks!

**Pull request merged**
