### PR TITLE
🚀 feat: Banner

### PR DESCRIPTION
**Pull request by ohneda**
## Summary

This PR proposes a banner feature to LibreChat. This feature is particularly useful for organizations using LibreChat that need to broadcast announcements to all users simultaneously.

I referred to the banner for https://librechat.ai/ (Nextra banner feature)

SCR-20240907-umqf

SCR-20240907-ujdo

## Details

* Manage banners using the `update-banner` script and `delete-banner` script.
* Banners have the following attributes:
    * bannerId
    * displayFrom: Display Start Date/Time
    * displayTo: Display End Date/Time
    * isPublic - false if the banner is only shown to logged-in users.
    * message(Plain text or HTML)
    * type - Currently supports `banner` only.
* Only one banner can be active at a time; adding a new banner will overwrite the existing one.
* The state (dismissed or not) of the banner is saved in `LocalStorage` using the `bannerId` as the key.
  
While this model could potentially support other message types like modal windows, the current implementation focuses solely on banners.

### Adding or Updating a Banner

To add or update a banner, use the following command:

```
npm run update-banner <displayFrom(Format: yyyy-mm-ddTHH:MM:SSZ)> <displayTo(Format: yyyy-mm-ddTHH:MM:SSZ)> <message> <isPublic(true/false)>
```

Example:
```
npm run update-banner 2024-09-01T00:00:00Z 2024-09-30T23:59:59Z '<a href="https://www.librechat.ai/changelog/v0.7.4" target="_blank">🎉 <span class="font-medium">Librechat 0.7.4</span> is released. Read more →</a>' true
```
Alternatively, if you don't specify any arguments, you can enter values interactively

### Removing a Banner

To remove the banner, use the following command:

```
npm run delete-banner
```

## Change Type

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Testing

I have manually verified the following:

* The `update-banner` script successfully adds or updates a banner.
* Only one banner document exists at a time.
* The `delete-banner` script removes the banner document.
* The background color of the banner varies with different themes.
* Clicking the "x" button dismisses the banner, and it remains dismissed after reloading the page.

## Checklist

Please delete any irrelevant options.

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] My changes do not introduce new warnings
- [x] Local unit tests pass with my changes

### CODE REVIEW

**Comment by berry-13** [comment]
@ohneda I like it, but I think it would be even better if you could implement a dialog that opens on the landing page. This way, you can include more text and provide clearer explanations for announcements.

**Comment by amir-ghasemi** [comment]
> @ohneda I like it, but I think it would be even better if you could implement a dialog that opens on the landing page. This way, you can include more text and provide clearer explanations for announcements.

Agreed. Something like the new terms and conditions modal would be great!

**Comment by ohneda** [comment]
@berry-13 Yes, this model can be generalized to dialog messages, so I will implement it once this PR is merged.

**Review by danny-avila — APPROVED** [review]

**Comment by hofq** [comment]
Really useful!
Can you provide an example on how to change the color?

**Comment by leondape** [comment]
I'm on latest (ded3cd88), ran `npm ci` and `run frontend`.  

Running `npm run update-banner` results in an exception: 
```
npm run update-banner

> LibreChat@v0.7.7 update-banner
> node config/update-banner.js

node:internal/modules/cjs/loader:1249
  throw err;
  ^

Error: Cannot find module '/Users/user/coding/librechat/api/models/schema/banner'
Require stack:
- /Users/user/coding/librechat/config/update-banner.js
    at Function.<anonymous> (node:internal/modules/cjs/loader:1246:15)
    at Module._resolveFilename (/Users/user/coding/librechat/node_modules/module-alias/index.js:49:29)
    at Function._load (node:internal/modules/cjs/loader:1072:27)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:216:24)
    at Module.require (node:internal/modules/cjs/loader:1337:12)
    at require (node:internal/modules/helpers:139:16)
    at Object.<anonymous> (/Users/user/coding/librechat/config/update-banner.js:5:16)
    at Module._compile (node:internal/modules/cjs/loader:1572:14)
    at Object..js (node:internal/modules/cjs/loader:1709:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/user/coding/librechat/config/update-banner.js' ]
}

Node.js v23.1.0
```

Did I do something wrong or is it a bug?

**Comment by Odrec** [comment]
> I'm on latest ([ded3cd8](https://github.com/danny-avila/LibreChat/commit/ded3cd8876501c1daa67d54bbb4b02d2b85efc3d)), ran `npm ci` and `run frontend`.
> 
> Running `npm run update-banner` results in an exception:
> 
> ```
> npm run update-banner
> 
> > LibreChat@v0.7.7 update-banner
> > node config/update-banner.js
> 
> node:internal/modules/cjs/loader:1249
>   throw err;
>   ^
> 
> Error: Cannot find module '/Users/user/coding/librechat/api/models/schema/banner'
> Require stack:
> - /Users/user/coding/librechat/config/update-banner.js
>     at Function.<anonymous> (node:internal/modules/cjs/loader:1246:15)
>     at Module._resolveFilename (/Users/user/coding/librechat/node_modules/module-alias/index.js:49:29)
>     at Function._load (node:internal/modules/cjs/loader:1072:27)
>     at TracingChannel.traceSync (node:diagnostics_channel:322:14)
>     at wrapModuleLoad (node:internal/modules/cjs/loader:216:24)
>     at Module.require (node:internal/modules/cjs/loader:1337:12)
>     at require (node:internal/modules/helpers:139:16)
>     at Object.<anonymous> (/Users/user/coding/librechat/config/update-banner.js:5:16)
>     at Module._compile (node:internal/modules/cjs/loader:1572:14)
>     at Object..js (node:internal/modules/cjs/loader:1709:10) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [ '/Users/user/coding/librechat/config/update-banner.js' ]
> }
> 
> Node.js v23.1.0
> ```
> 
> Did I do something wrong or is it a bug?

Seems the banner schema disappeared from the project: https://github.com/danny-avila/LibreChat/tree/main/api/models/schema

**Comment by Odrec** [comment]
> thank you for the prompt analysis. Then I'll wait until the issue gets closed :)

I found it! It seems there was a refactoring last week and the schema was moved here: https://github.com/danny-avila/LibreChat/blob/main/packages/data-schemas/src/schema/banner.ts

**Pull request merged**
