### PR TITLE
update GOOGLE_MODELS in .env.example

### PR DESCRIPTION
**Pull request by kneelesh48**
# Pull Request Template

## Summary

update GOOGLE_MODELS in .env.example fetched from the Google API and verified
These changes have been made in the [documentation](https://docs.librechat.ai/install/configuration/ai_setup.html#generative-language-api-gemini) but not in this file

## Change Type

Please delete any irrelevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)

## Testing

Please describe your test process and include instructions so that we can reproduce your test. If there are any important variables for your testing configuration, list them here.

## Checklist

Please delete any irrelevant options.

- [ ] My code adheres to this project's style guidelines
- [ ] I have performed a self-review of my own code
- [ ] I have commented in any complex areas of my code
- [ ] I have made pertinent documentation changes
- [ ] My changes do not introduce new warnings
- [ ] I have written tests demonstrating that my changes are effective or that my feature works
- [ ] Local unit tests pass with my changes
- [ ] Any changes dependent on mine have been merged and published in downstream modules.
- [ ] New documents have been locally validated with mkdocs

### CODE REVIEW

**Comment by danny-avila** [comment]
the models in the example are for vertex ai, maybe make a distinction instead?

**Comment by kneelesh48** [comment]
> the models in the example are for vertex ai, maybe make a distinction instead?

I tested, these models work for Google AI Studio API

**Comment by danny-avila** [comment]
> > the models in the example are for vertex ai, maybe make a distinction instead?
> 
> I tested, these models work for Google AI Studio API. I'm only using Google AI Studio API, don't have Vertex AI



> > the models in the example are for vertex ai, maybe make a distinction instead?
> 
> I tested, these models work for Google AI Studio API. I'm only using Google AI Studio API, don't have Vertex AI

I meant the models you're replacing. see the docs here: 

https://docs.librechat.ai/install/configuration/ai_setup.html#generative-language-api-gemini

https://docs.librechat.ai/install/configuration/ai_setup.html#click-on-add-key-and-then-create-new-key

**Comment by kneelesh48** [comment]
I got your point
The models listed at https://docs.librechat.ai/install/configuration/ai_setup.html#generative-language-api-gemini are for Google AI Studio API
And the models listed at https://docs.librechat.ai/install/configuration/ai_setup.html#click-on-add-key-and-then-create-new-key are for Vertex AI

And the models listed in GOOGLE_MODELS .env.example are for Vertex AI

Maybe we can have two environment variables 
GOOGLE_MODELS for Google AI Studio API 
and GOOGLE_VERTEX_MODELS for Vertex AI.

Or we can put Vertex AI models in librechat.yml similar to Open AI and Azure Open AI case.
I think Google AI Studio should be the main one in .env since it's the more accessible one.

I also suggess putting the documentation for Vertex AI in a separate page similar to Azure OpenAI.

What do you think?
I can work on a PR for this, just let me know

**Comment by danny-avila** [comment]
> Maybe we can have two environment variables GOOGLE_MODELS for Google AI Studio API and GOOGLE_VERTEX_MODELS for Vertex AI.

> What do you think? I can work on a PR for this, just let me know

2 variables I don't agree with, because it's an either/or setup. just two examples in the .env.example would be great, indicating which is which.

> I also suggest putting the documentation for Vertex AI in a separate page similar to Azure OpenAI.

Yes if you'd like to, I'd welcome this!

**Comment by kneelesh48** [comment]
I've updated this PR with two GOOGLE_MODELS, one for Gemini API, other for Vertex AI. I recommened making Gemini API the default one since it's the more accessible one. Setting up Vertex AI is more complex requiring a Google Cloud account, setting up billing and enabling APIs in Google Cloud.

**Comment by danny-avila** [comment]
I improved the formatting a bit. thanks for this!

**Pull request merged**
