### PR TITLE
style: HoverButton UI adjustment, change code font

### PR DESCRIPTION
**Pull request by SailFlorve**
# Pull Request Template

## Summary

Just like the official ChatGPT, the HoverButton should only be displayed under the last message, and other messages need to be  hovered to display. In this way, the entire chat UI will not be so bloated. 
And I changed the code font to Consolas, which is like the official ChatGPT, and the code is more pretty.

Before
image
After
image

Before
image

after
image

## Change Type

Please delete any irrelevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation update
- [ ] Translation update

## Testing

Please describe your test process and include instructions so that we can reproduce your test. If there are any important variables for your testing configuration, list them here.

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [ ] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [ ] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [ ] Any changes dependent on mine have been merged and published in downstream modules.

### CODE REVIEW

**Comment by Berry-13** [comment]
@SailFlorve can you please merge all these changes into 1 PR? 
#2014
#2013

**Comment by Berry-13** [comment]
also, share some screenshots of the before/after, here's an example: #1199

**Comment by SailFlorve** [comment]
> @SailFlorve can you please merge all these changes into 1 PR? #2014 #2013

I thought this not easy to test, so I categorized it into different PRs.

**Comment by Berry-13** [comment]
> > @SailFlorve can you please merge all these changes into 1 PR? #2014 #2013
> 
> I thought this not easy to test, so I categorized it into different PRs.

if you specify the changes before/after, it's also easier for us to review and see differences. also, commits in LibreChat should instantly explain the changes, if they are all style updates they can be merged without creating 3 different commits

**Comment by SailFlorve** [comment]
> if you specify the changes before/after, it's also easier for us to review and see differences. also, commits in LibreChat should instantly explain the changes, if they are all style updates they can be merged without creating 3 different commits

I've uploaded the images, but I don't know how to merge the PRs because this is my first time submitting PR. I'll keep this in mind.

**Comment by Berry-13** [comment]
> > if you specify the changes before/after, it's also easier for us to review and see differences. also, commits in LibreChat should instantly explain the changes, if they are all style updates they can be merged without creating 3 different commits
> 
> I've uploaded the images, but I don't know how to merge the PRs because this is my first time submitting PR. I'll keep this in mind.

I think that if it's necessary Danny will merge them in some way. That was just a suggestion for future PRs, thanks!

**Comment by danny-avila** [comment]
It's okay not to merge the PRs. Actually I prefer they are separated by scope. Thanks for the PR!

**Comment by itzraiss** [comment]
Only after opening my PR #2046 did I realize that it covered the same thing as mine. If you're interested, my PR includes changing the color of the Rename and Delete buttons for light and dark themes, as well as highlighting when a conversation is focused or selected, similar to ChatGPT. Do you think it would be interesting to merge this PR?

**Comment by danny-avila** [comment]
Some conflicts before I can approve

**Pull request merged**
