### PR TITLE
🗨️ feat: Prompt Slash Commands

### PR DESCRIPTION
**Pull request by danny-avila**
## Summary

I implemented a new feature that allows users to access prompts directly from the main chat input using slash commands, inspired by Discord's slash command functionality. This enhancement streamlines the user experience by providing quick access to predefined prompts without leaving the chat interface.

- Integrated the slash command feature with the existing chat commands
- Added new UI elements to display available commands and their descriptions
- Allows user to specify command when editing/creating prompts

### Other Changes

- Moved Assistants builder to top of side panel when Assistants are active 
- allow defining emailVerified via create-user script

## Change Type

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes

### CODE REVIEW

**Comment by joihn** [comment]
any way to disable this feature ?
I frequently input linux path `/path/to/dir` and this feature make it difficult

**Comment by berry-13** [comment]
> any way to disable this feature ? I frequently input linux path `/path/to/dir` and this feature make it difficult

no but in the meantime you can add a backtick before the slash, like this:

```
`/path/to/dir`
```

**Comment by TIAcode** [comment]
+1 for the disabling. The popup is really annoying to close, so I bound '/' to 'a/' in my browser to avoid it and then go back to remove the extra character.

**Comment by danny-avila** [comment]
> +1 for the disabling. The popup is really annoying to close, so I bound '/' to 'a/' in my browser to avoid it and then go back to remove the extra character.

Likely an option to disable, but it also would make sense to only allow characters from the first character position

**Comment by adamhcj** [comment]
I managed to disable this feature with a simple way, by forcing the conditions of the 3 show commands to be `false`:

image
image

**Comment by mkagit** [comment]
I need to disable the `@` but keep the `/`. Don't want to change the code. Being able to disable from the interface UI in the yaml?

**Comment by danny-avila** [comment]
@mkagit check UI settings 

firefox_zde30eeqYm

**Comment by mkagit** [comment]
Thanks @danny-avila, I see but I would like to disable for all users from the yaml. @ keeps showing old endpoints and agents no more active, it's confusing.
By the way, I would like being able to set all users settings from the yaml for all users.
For beginners the setting panel is overwhelming, it's better the Admin set for them internally.

**Pull request merged**
