### PR TITLE
🌿 fix: forking a long conversation breaks chat structure

### LINKED ISSUE #4761: [Bug]: Saved conversation structure collapse
### What happened?

I had a long conversation saved last week. That conversation had occasional branching where i edited my questions. Never more than a couple of branches wide, max 3 or 4. Now it is showing as if the entire conversation has one message at the trunk, and 42 branches on the same level. When i click on the < and > to navigate between these branches, it actually changes the root message, which is sometimes mine sometimes the LLM's answer!

I tried on both local / running on docker and on hugginface. They're both using the same DB so i guess there is corruption at the DB level. WHICH IS VERY SCARY.

image

### Steps to Reproduce

I noticed this today I tried to find a message in that conversation so searched for a term in the search bar, it listed the relevant messages and the correct conversation. When I clicked on it, I found that the normal tree structure of the conversation had totally collapsed into a single trunk with 42 branches.

### What browsers are you seeing the problem on?

Chrome

### Relevant log output

```shell
The log shows 200 messages loaded. but i don't see them except by navigating using the < 40/42 > prompt paginator.
```

### Screenshots

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by danny-avila**
ref: PR https://github.com/danny-avila/LibreChat/pull/4772

Closes https://github.com/danny-avila/LibreChat/issues/4761

Originally https://github.com/danny-avila/LibreChat/pull/4777

### CODE REVIEW

**Comment by xyqyear** [comment]
Is it possible to reference the same buildTree function in the tests instead of duplicating the code? Changes made to buildTree would have to be reflected in two different places. 

Another thing is, this change would make imported (from file) messages not having createdAt field, which mighe become problematic when in the future we call
 something like "deletedOlderThan". We might need to add createdAt manually when importing from files (adding incremental createdAt field when not existed or converting from original timestamp.).

@danny-avila

**Comment by danny-avila** [comment]
@xyqyear 

> Is it possible to reference the same buildTree function in the tests instead of duplicating the code? Changes made to buildTree would have to be reflected in two different places.

I don't plan on changing this function, and it's really not needed in the backend except for this test with the database logic, so it's not worth it to me.

> Another thing is, this change would make imported (from file) messages not having createdAt field, which mighe become problematic when in the future we call
something like "deletedOlderThan". We might need to add createdAt manually when importing from files (adding incremental createdAt field when not existed or converting from original timestamp.).

can you elaborate more on this? I think this would be simple to handle the edge case here then:

https://github.com/danny-avila/LibreChat/blob/7a5b697627eef1103a4c1897529b57549eca54dd/api/server/utils/import/importBatchBuilder.js#L99-L110

to this:

```cjs
  async saveBatch() {
    try {
      // Set default timestamp for messages that don't have one
      const defaultTimestamp = new Date();
      this.messages = this.messages.map(message => ({
        ...message,
        createdAt: message.createdAt || defaultTimestamp,
        updatedAt: message.updatedAt || defaultTimestamp
      }));

      await bulkSaveConvos(this.conversations);
      // Keep overrideTimestamp as true to use our explicitly set timestamps
      await bulkSaveMessages(this.messages, true);
      logger.debug(
        `user: ${this.requestUserId} | Added ${this.conversations.length} conversations and ${this.messages.length} messages to the DB.`,
      );
    } catch (error) {
      logger.error('Error saving batch', error);
      throw error;
    }
  }
}
```

**Comment by danny-avila** [comment]
also maybe the above needs to be adjusted to account for child messages not being earlier than parent messages

**Comment by xyqyear** [comment]
@danny-avila 

Absolutely! Changing `saveBatch` like that to account for edge cases is the best way to do it for now imo.

> also maybe the above needs to be adjusted to account for child messages not being earlier than parent messages

This could be accomplished by https://github.com/danny-avila/LibreChat/pull/4772/commits/d38953b44da2a645a7dc64bda57aca260641f7dd However, through testing, this will make the page unresponsive for some reason. But if it's done correctly, the previously broken conversations could be fixed as well.

**Pull request merged**
