### PR TITLE
Initial attempt at testing openidStrategy and adding OPENID_USERNAME_CLAIM setting

### PR DESCRIPTION
**Pull request by alihacks**
## Summary

Adding tests for openidStrategy  and additional configuration for openid username and name claims. This is an early PR for feedback, I will be implementing more tests and configuration - would like feedback early on before proceeding.

## Change Type

Please delete any irrelevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [X] This change requires a documentation update
- [ ] Translation update

## Testing

Test with local OIDC provider and jest tests.

## Checklist

Please delete any irrelevant options.

- [X] My code adheres to this project's style guidelines
- [X] I have performed a self-review of my own code
- [X] I have commented in any complex areas of my code
- [ ] I have made pertinent documentation changes
- [X] My changes do not introduce new warnings
- [X] I have written tests demonstrating that my changes are effective or that my feature works
- [X] Local unit tests pass with my changes
- [ ] A pull request for updating the documentation has been submitted.

### CODE REVIEW

**Comment by danny-avila** [comment]
Thanks for doing this! You can also use `mongodb-memory-server` for the database operations, see an example in `api/models/Role.spec.js`

**Comment by alihacks** [comment]
> Thanks for doing this! You can also use `mongodb-memory-server` for the database operations, see an example in `api/models/Role.spec.js`

For some reason, when I try the exact same pattern as Role.Spec.js, I get "Client must be connected before running operations" when code is trying to access mongoose from the validate method. But I can connect to the memory server and run queries no problem. Not sure why this is the case.

**Comment by alihacks** [comment]
Updated tests to use `mongodb-memory-server`

**Comment by danny-avila** [comment]
can you also add documentation for this and the other PR?

**Comment by alihacks** [comment]
> can you also add documentation for this and the other PR? https://github.com/LibreChat-AI/librechat.ai

Sure - I had a question about where the doc for additional OIDC config should live. They're not provider specific but it seems all the generic options are documented under keycloak - is that where you want these documented?

**Comment by danny-avila** [comment]
> Sure - I had a question about where the doc for additional OIDC config should live. They're not provider specific but it seems all the generic options are documented under keycloak - is that where you want these documented?

Any help to the end of making a generic page is appreciated.

I will push all your changes with the next release cycle.

**Comment by danny-avila** [comment]
Replaced by #4561

**Pull request closed without merging**
