### PR TITLE
📝 feat: Markdown support for Custom Footer links

### PR DESCRIPTION
**Pull request by jakubmieszczak**
## Summary

This PR addresses enhancements requested issue [#(2959)](https://github.com/danny-avila/LibreChat/discussions/2959) regarding adding support for markdown hyperlinks in footer environment variables. Previously, markdown links added in these environment variables were rendered as plain text. With these changes, the application now correctly interprets and displays these links.

## Change Type

Please delete any irrelevant options.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Testing
This was tested on several cases. Works fine for single and multiple markdowns.

To test these changes, add a markdown link in the `CUSTOM_FOOTER` environment variable and confirm that the link is correctly interpreted and displayed in the footer by the application.

Example markdown:

`CUSTOM_FOOTER="Internal [ChatGPT documentation](https://placeholder-link.com)"`

### **Test Configuration**:

1. Add a markdown link to the CUSTOM_FOOTER environment variable and save changes.
2. Run the application.
3. Navigate to main page that displays the footer.
4. Confirm that the markdown link added in the environment variable shows as a clickable hyperlink in the footer.

## Checklist

Please delete any irrelevant options.

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.
- [x] A pull request for updating the documentation has been submitted.

### CODE REVIEW

**Comment by Tanvez** [comment]
Tested and seems to work correctly from testing
Few things i noticed: 
- When adding a pipe between links the format isn’t matching the `privacyPolicy` and `termsOfservice` size
- If no link is provided, it will redirect back to the chat window(I guess that is fine for now)
- Theres some spacing issue with the custom footer and `privacyPolicy`  and `termsOfservice`  in mobile view
Screenshot 2024-06-06 at 2 25 42 PM

Screenshot 2024-06-06 at 2 22 23 PM

**Comment by danny-avila** [comment]
> When adding a pipe between links the format isn’t matching the privacyPolicy and termsOfservice size

Good catch @Tanvez.

@jakubmieszczak maybe you can map any occurrence of ` | ` to separator elements?

```ts
<div key={`separator-${index}`} className="h-2 border-r-[1px] border-gray-300" />
```

> Theres some spacing issue with the custom footer and privacyPolicy and termsOfservice in mobile view

The prior comment may help resolve this issue. I can try to address it if you don't figure it out. The important thing would be to allow the custom footer render to possibly be made up of multiple elements on the same plain as privacy/tos

---

Only other comment I have is that `client/src/components/Input/Footer.tsx` is no longer used, and you can actually delete it as part of this PR

**Comment by jakubmieszczak** [comment]
I've addressed the proposed changes in this PR. 

- All links in the footer are now displayed horizontally next to each other, rather than vertically one on top of another.
- I've removed the unused `client/src/components/Input/Footer.tsx` file to clean up our repository.
- The pipe characters have been correctly converted into div elements so they're visually consistent with the rest of the layout.
- Text across all sections in footer is aligned to center.

Please let me know if there are any further changes required. Thank you for your feedback @danny-avila !

image

Screenshot 2024-06-11 at 14 01 39

**Comment by danny-avila** [comment]
> I've addressed the proposed changes in this PR.
> 
>     * All links in the footer are now displayed horizontally next to each other, rather than vertically one on top of another.
> 
>     * I've removed the unused `client/src/components/Input/Footer.tsx` file to clean up our repository.
> 
>     * The pipe characters have been correctly converted into div elements so they're visually consistent with the rest of the layout.
> 
>     * Text across all sections in footer is aligned to center.
> 
> 
> Please let me know if there are any further changes required. Thank you for your feedback @danny-avila !

thank you @jakubmieszczak looks good to me!

All I would ask if you would kindly make a PR here to add an additional note for using markdown with CUSTOM_FOOTER

https://www.librechat.ai/docs/configuration/dotenv#app-title-and-footer
https://github.com/LibreChat-AI/librechat.ai/blob/main/pages/docs/configuration/dotenv.mdx

**Comment by jakubmieszczak** [comment]
Can we merge this PR and include changes in `v0.7.3`? @danny-avila

**Review by danny-avila — APPROVED** [review]

**Pull request merged**
