### PR TITLE
🛂 feat: Allow LDAP login via username

### PR DESCRIPTION
**Pull request by lkiesow**
This patch adds the option to login via username instead of using an email address since the latter may not be unique or may change.

For example, our organization has two main domains and users have a log and a short form of their mail address. This makes it hard for users to identify what their primary email address is and causes a lot of confusion. Using their username instead makes it much easier.

Using a username will also make it easier in the future to not need a separate bind user to get user attributes. So, this is also a bit of prep work for that.

Screenshot from 2024-07-04 17-12-14
*Login page asking for username instead of email*

## Change Type

Please delete any irrelevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [ ] Translation update

## Testing

- Configure LDAP
- Set `LDAP_LOGIN_USES_USERNAME=true`
- You will likely want to set something like `LDAP_SEARCH_FILTER="uid={{username}}"`

After starting backend and frontend, you should see the login page asking for a username instead of an email.

## Checklist

Please delete any irrelevant options.

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [ ] I have written tests demonstrating that my changes are effective or that my feature works
- [ ] Local unit tests pass with my changes
- [ ] Any changes dependent on mine have been merged and published in downstream modules.
- [x] [A pull request for updating the documentation has been submitted](https://github.com/LibreChat-AI/librechat.ai/pull/84).

### CODE REVIEW

**Comment by danny-avila** [comment]
Thanks for updating the documentation. I made a slight edit, please confirm it works as expected

**Comment by lkiesow** [comment]
The edit looks good. It definitely makes sense to use `isEnabked(…)`. I did miss that the utility function exists. Sorry.

**Review by danny-avila — APPROVED** [review]

**Comment by lkiesow** [comment]
Hi @danny-avila, can you merge this?

**Comment by danny-avila** [comment]
Thanks there was a couple of type issues and thinking about potential ways to reduce the size of this particular object and organize the different configurations, continued and merging this: https://github.com/danny-avila/LibreChat/pull/3463

**Pull request closed without merging**
