### PR TITLE
🌍 i18n: Updated Chinese Translation

### PR DESCRIPTION
**Pull request by zjjxwhh**
## Summary

1. Recreated the Zh.ts file using the latest Eng.ts file (because the key-value pairs in the original Zh.ts file were completely out of order compared to Eng.ts, making it difficult for me to compare the missing key-value pairs). 
2. Updated the Chinese translations based on the content of the original Zh.ts file.

Since I don't know how to create export const comparisons = {...}, the new Zh.ts file only contains export default {...}. However, I didn't encounter any errors during local testing. If it's necessary, please let me know how to create it. Thank you very much!

## Change Type

- [x] Translation update

## Testing

Clone the code, run the backend and frontend, modify Zh.ts, and test.

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works

### CODE REVIEW

**Comment by zjjxwhh** [comment]
May I ask if the "Edge" option under **Settings - Speech - Text to Speech - Engine** refers to the Microsoft Edge browser? I haven't used Text to Speech before, so I'm not quite sure what it specifically means.

**Comment by danny-avila** [comment]
> May I ask if the "Edge" option under Settings - Speech - Text to Speech - Engine refers to the Microsoft Edge browser? I haven't used Text to Speech before, so I'm not quite sure what it specifically means.

Edge refers to cloud edge computing

**Comment by danny-avila** [comment]
thank you for your contribution! let me know if this is ready merge

**Comment by zjjxwhh** [comment]
@danny-avila Thanks for your explanation. I have updated the corresponding translation and is ready merge.

(Additionally, I noticed that some languages, like Korean, have translated the com_nav_lang_xxx fields. I think these fields should not be translated because it makes it difficult for non-Korean speakers to change the language in the settings, as they may not know that "영어" means "English" and "중국어" means "Chinese.")

**Comment by danny-avila** [comment]
> (Additionally, I noticed that some languages, like Korean, have translated the com_nav_lang_xxx fields. I think these fields should not be translated because it makes it difficult for non-Korean speakers to change the language in the settings, as they may not know that "영어" means "English" and "중국어" means "中文(Chinese).")

This is true, if you're willing to help with the change, I am very open to changing that.

**Pull request merged**
