### PR TITLE
🔧 fix: Drop openai version to fix API.Batches is not a constructor error

### PR DESCRIPTION
**Pull request by abdalrohman**
## Summary

This pull request addresses an issue where `API.Batches` was not being recognized as a constructor in some API endpoints. The root cause was identified as a compatibility problem with the OpenAI SDK version `4.36.0`.

## Change Type

- [x] Bug fix (non-breaking change which fixes an issue)

### CODE REVIEW

**Comment by danny-avila** [comment]
When do you observe this error?

**Comment by abdalrohman** [comment]
When i use groq, cohere, OpenRouter endpoints...

**Comment by abdalrohman** [comment]
When i use groq, cohere, open endpoints...

**Comment by abdalrohman** [comment]
These errors indicate that the AI model is unable to process the request due to an issue with the OpenAI API and the API.Batches constructor. By dropping the pinned version of the openai package and allowing a broader version range, we ensure compatibility and resolve the constructor error. This should enable the AI model to function as expected without encountering the API.Batches-related issue.

{"level":"error","message":"[loadAndFormatTools] Error initializing `DALLE3.js` tool; if it requires authentication, is the `override` field configured? API.Batches is not a constructor","stack":"TypeError: API.Batches is not a constructor\n

{"level":"error","message":"[OpenAIClient.chatCompletion] Unhandled error type API.Batches is not a constructor","stack":"TypeError: API.Batches is not a constructor\n

{"level":"error","message":"[handleAbortError] AI response error; aborting request: API.Batches is not a constructor","stack":"TypeError: API.Batches is not a constructor\n

**Comment by danny-avila** [comment]
> These errors indicate that the AI model is unable to process the request due to an issue with the OpenAI API and the API.Batches constructor. By dropping the pinned version of the openai package and allowing a broader version range, we ensure compatibility and resolve the constructor error. This should enable the AI model to function as expected without encountering the API.Batches-related issue.
> 
> {"level":"error","message":"[loadAndFormatTools] Error initializing `DALLE3.js` tool; if it requires authentication, is the `override` field configured? API.Batches is not a constructor","stack":"TypeError: API.Batches is not a constructor\n
> 
> {"level":"error","message":"[OpenAIClient.chatCompletion] Unhandled error type API.Batches is not a constructor","stack":"TypeError: API.Batches is not a constructor\n
> 
> {"level":"error","message":"[handleAbortError] AI response error; aborting request: API.Batches is not a constructor","stack":"TypeError: API.Batches is not a constructor\n

I asked because I'm not able to reproduce this issue, using DALL-E or any other process via the OpenAI SDK. Ideally, I would like to keep it at 4.36.0 because it is the last version before Assistants v2 is adopted. 

The project does not make use of Batching either, so this is confusing.

Also,

> "openai": "^4.29.0",

This implicitly allows version beyond 4.36.0 on npm install

**Comment by danny-avila** [comment]
I recommend you run `npm run reinstall` when re-installing, or after upgrading, as this is not an issue when doing so.

**Comment by danny-avila** [comment]
## openrouter

image

## groq
image


## cohere

image

**Pull request closed without merging**
