### PR TITLE
🚀 feat: gpt-4o

### LINKED ISSUE #2693: [Question]: Inquiry on the Availability of ver GPT-4o API
### What is your question?

I am writing to enquire about the roadmap for the GPT API, specifically regarding the release of a GPT-4o version.  the capabilities of the GPT models are critical to the progress and efficiency of my projects.

Please give as many details as possible:
I have been utilizing the current version available, and I'm eager to understand what improvements and new features GPT-4 will bring. 

### More Details

If there is a timeline or any planned release date for GPT-4o, as well as details on how we can prepare to integrate the new API version, it would be immensely helpful.

 
The main subject of my question is the release schedule and feature set of the upcoming GPT-4o API.

### What is the main subject of your question?

Other

### Screenshots

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by danny-avila**
Closes #2693

### CODE REVIEW

**Comment by MrMebelMan** [comment]
That was fast :D
Thanks <3

**Comment by kneelesh48** [comment]
They are going to change the ChatGPT UI to incorporate for audio and image input capabilities of gpt-4o, also audio and image output without using a tts model.

We're gonna have to change LibreChat as well since it claims to be a ChatGPT clone.

Also, we should prioritise https://github.com/danny-avila/LibreChat/pull/1603 to enable TTS and STT capabilities because gpt-4o will naturally have it and the code implementation will also be different.

Just my 2 cents

**Comment by RedwindA** [comment]
tokenizer should be update too
https://github.com/openai/tiktoken/commit/c0ba74c238d18b4824c25f3c27fc8698055b9a76

**Comment by danny-avila** [comment]
> They are going to change the ChatGPT UI to incorporate for audio and image input capabilities of gpt-4o, also audio and image output without using a tts model.
> 
> We're gonna have to change LibreChat as well since it claims to be a ChatGPT clone.
> 
> Also, we should prioritise #1603 to enable TTS and STT capabilities because gpt-4o will naturally have it and the code implementation will also be different.
> 
> Just my 2 cents

See https://github.com/danny-avila/LibreChat/discussions/2696

**Comment by danny-avila** [comment]
> tokenizer should be update too [openai/tiktoken@c0ba74c](https://github.com/openai/tiktoken/commit/c0ba74c238d18b4824c25f3c27fc8698055b9a76)

Thanks, will look into this

**Comment by alexlyzhov** [comment]
When I created a huggingface space duplicate today, `gpt-4o` wasn't in the default for OPENAI_MODELS env variable in space settings; it worked after I added it manually.

**Pull request merged**
