### PR TITLE
Feature support export conversation

### PR DESCRIPTION
**Pull request by wtlyu**
Support: 

- [x] text
- [x] markdown
- [x] json
- [x] csv
- [x] screenshot
- [x] webpage (give up, do it in future)

### CODE REVIEW

**Comment by wtlyu** [comment]
## To Text


image


## To JSON




## To Markdown




## To CSV





## To Screenshot

**Comment by danny-avila** [comment]
webpage too?? wow!

**Comment by wtlyu** [comment]
> webpage too?? wow!

in plan but haven't think clear.

**Comment by danny-avila** [comment]
ok we back to normal, is this ready to merge? i know you said export to webpage will be too complicated

**Review by danny-avila — APPROVED** [review]

**Pull request merged**
