### PR TITLE
🔖 feat: Conversation Bookmarks

### LINKED ISSUE #3388: Enhancement: Star/PIN Messages to keep them on top
### What features would you like to see added?

Star/PIN Messages to keep them on top

### More details

I'd like the ability to star messages to keep them on top.
E.g. a "coach" or pair-conversation for an active project.

### Which components are impacted by your request?

UI

### Pictures

image

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by ohneda**
## Summary

This pull request introduces the following bookmark features:

* Conversation bookmarks  
* Manage multiple bookmarks
* Display only specific bookmarked conversations

## Change Type

- [x] New feature (non-breaking change which adds functionality)

UI design is not my strong suit, so it may not be as intuitive as desired. Please feel free to provide feedback or make changes where necessary.

### Bookmark a conversation

* Click on the bookmark icon while viewing a conversation to add it to the "Saved" bookmarks.

https://github.com/user-attachments/assets/0c55ddc2-fd90-43c4-a63c-1d554d85f630

### Add a new bookmark

* Open the bookmark table from the header bookmark menu or the side panel.
* Click the "Add new bookmark" button, fill out the form with the necessary information, and submit.

https://github.com/user-attachments/assets/44108718-e33e-4296-bec8-f05b82667e7d

### Add to existing bookmarks

* If a conversation is already bookmarked, clicking the bookmark menu icon will display a list of your bookmarks.
Click on the desired bookmark to add the conversation to it.

https://github.com/user-attachments/assets/82dd7365-cda7-4021-a468-c3c4a9ef9ff0

### Reorder bookmarks

* Open the bookmark table from the side panel and adjust the order as preferred.

https://github.com/user-attachments/assets/879debc5-b509-4a46-8f85-d64c68ec86e2

### Edit a bookmark

* Open the bookmark table from the side panel's bookmark menu, and click the Edit button to modify a bookmark.

https://github.com/user-attachments/assets/90a4f2e4-dc8b-47da-9eb4-cde4da02fd79

### Delete a bookmark

* Open the bookmark table from the side panel, click the Delete button, and delete the bookmark.
* Deleting a bookmark also removes it from any conversations it's associated with.

https://github.com/user-attachments/assets/1e646641-065c-4926-9837-7635e7fe63c9

### Display Specific Bookmarks

* Select the desired bookmarks from the navigation menu.
* Multiple bookmarks can be selected to display conversations associated with them.
* Only conversations tagged with the selected bookmarks will be shown.

https://github.com/user-attachments/assets/15ed3e0d-e1ba-4632-8b35-dca168c63ecc

### Rebuild Bookmark Counts

If the count of bookmarked conversations seems incorrect, rebuild the counts. Despite extensive testing, there may still be bugs causing synchronization issues between ConversationTags and conversations. This rebuild button is a precaution and may become obsolete once bookmark bugs are fully resolved.

https://github.com/user-attachments/assets/fa4a533f-4fb8-4e0c-ad5f-9b366d3fbda3

## Implementation details

* Added a `tags` attribute to Conversations, which is an array of strings.
* On the client side, these tags are represented as Bookmarks. Terms like Collection, Library, Favorite, or Save might be more appropriate; adjustments can be made as necessary.
* Although each tag in Conversation is a string, a new model called `ConversationTag` was added to store metadata.
  * `ConversationTag` includes attributes such as `tag`, `description`, `count`, and `position`. Future extensions might involve adding `color` or `icon` attributes.
* The `tag` attribute in `ConversationTag` is used as a unique identifier
* Currently, after creating, updating, or deleting a Bookmark (tag), the client-side query cache is updated to reflect these changes. Since this process complicates the logic, always refetching instead of updating the cache might be a simpler solution.

```mermaid
classDiagram
    class Conversation {
        +String[] tags
    }
    class ConversationTag {
        +String tag
        +String description
        +Number count
        +Number position
    }
    Conversation "1" *-- "0..*" ConversationTag : contains
    Conversation "0..*" --> "0..*" ConversationTag : tags reference
    note for Conversation "tags is a collection of ConversationTag.tag values"
    note for ConversationTag "count represents the number of Conversations\nthat include this tag in their tags array"
```

## Testing

All features have been thoroughly tested to ensure proper functionality. I also verified that existing features have not been degraded as much as possible.

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] My changes do not introduce new warnings
- [x] Local unit tests pass with my changes

### CODE REVIEW

**Comment by danny-avila** [comment]
thanks!

how secure are the bookmarks? Is it possible to share them?

**Comment by ohneda** [comment]
Bookmarks are linked to individual users, so only the owner of the bookmark can view them. Sharing with other users is not possible at this time.

**Comment by danny-avila** [comment]
Will merge as soon as conflict is resolved. I'm not able to resolve right this moment

**Comment by ohneda** [comment]
@danny-avila resolved

**Review by danny-avila — APPROVED** [review]

**Comment by danny-avila** [comment]
@ohneda just thinking about this after using, I don't like that there's a button to "rebuild", it should auto-rebuild, either post-bookmark or pre-bookmark. No disrespect to them. but some users don't even know how to configure a model.

Overall, bulk operations should be used, if latency is a concern, and the Model `save()` method should never be used.

Also seems rather complex for groupings to track position in the database.

---

I'm thankful this feature is in but the current design needs a revisit, at the very least the rebuild process.

**Comment by danny-avila** [comment]
From @berry-13's testing, the rebuild button can be spammed and cause slowdowns, it should not be relegated to a user invocation.

**Comment by ohneda** [comment]
@danny-avila Thanks for your feedback. If you haven't started on it yet, I think I can work on it today.

**Comment by ohneda** [comment]
Hi @berry-13 , In this PR, it seems that the backend API is not called when the order of the bookmarks is changed by D&D. Is this intentional? Or can I fix this?

**Comment by danny-avila** [comment]
> @danny-avila Thanks for your feedback. If you haven't started on it yet, I think I can work on it today.

Thanks for taking the time to revisit this.

I will take a stab later today just optimizing the backend operations but it would be post-release at this point

**Comment by danny-avila** [comment]
@ohneda got around to it, this addresses my main concerns: https://github.com/danny-avila/LibreChat/pull/3590

**Pull request merged**
