### PR TITLE
🗨️ feat: Prompts

### LINKED ISSUE #3128: [Bug]: The l10n string `com_ui_upload_invalid` incorrectly hardcodes a 2 MB file size limit.
### What happened?

While `avatarSizeLimit` can be freely changed and works as intended, the error message always indicates that the limit is 2 megabytes:

image
image

Turns out, that it is hardcoded in the string itself:
```
com_ui_upload_invalid: 'Invalid file for upload. Must be an image not exceeding 2 MB',
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by danny-avila**
### Summary

I implemented the initial features for the Prompt Library, enhancing prompt management capabilities as proposed in issue #3023. This includes functionalities for creating, using, and sharing prompts, as well as admin-specific controls and categorization.

- Implemented ability to create and use prompts easily.
- Added support for prompts to have "fill-in" variables.
- Created special variables for current date and current user.
- Enabled users to share prompts globally.
- Provided quick and easy access to prompts from the side panel.
- Added filtering functionality for prompts.
- Implemented advanced and optional versioning of prompts.
- Enabled categorization and labeling of prompts.
- Allowed admins to share prompts globally.
- Enabled admins to restrict user prompt creation.
- Allowed admins to add categories for prompts.

### Testing

To ensure the implemented features are working correctly:
 
1. Create a prompt and verify its usability within a chat.
2. Use fill-in variables within a prompt and confirm correct substitution.
3. Share a prompt globally and check its visibility to other users.
4. Access prompts from the side panel and verify quick access functionality.
5. Filter prompts and confirm accurate results.
6. Test versioning by creating multiple versions of a prompt.
7. Categorize prompts and check if they are listed under the correct labels.
8. Admins should try sharing and restricting user prompts and adding categories.

### Test Configuration:

- Test different user roles (admin, regular user).
- Ensure prompts work across various chat endpoints.
- Verify prompt management functionalities in different browsers.

### Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes

Also closes  #3128

### CODE REVIEW

**Comment by spdustin** [comment]
Holy hell, Danny, you're on fire.

**Comment by danny-avila** [comment]
> Holy hell, Danny, you're on fire.

Thanks! About to merge this.

**Comment by dannykorpan** [comment]
Quick Question: Is it already possible to share a prompt?

**Comment by danny-avila** [comment]
> Quick Question: Is it already possible to share a prompt?

Yes, try it

**Comment by danny-avila** [comment]
you can do it when editing prompts:

image

**Comment by danny-avila** [comment]
Admin (the first created user) needs to enable the option 

image


image

**Comment by dannykorpan** [comment]
Thank you, this trick did it.

**Pull request merged**
