### PR TITLE
👟 style: CodeAnalyze Animation

### PR DESCRIPTION
**Pull request by walbercardoso**
## Summary

SVG animation effect like on ChatGPT

https://github.com/danny-avila/LibreChat/assets/50842245/a6fff83a-406a-4c6b-bb73-7e427c0fcf68

## Change Type

Please delete any irrelevant options.

- [X] Bug fix (non-breaking change which fixes an issue)

Please delete any irrelevant options.

- [X] My code adheres to this project's style guidelines
- [X] I have performed a self-review of my own code
- [X] I have commented in any complex areas of my code
- [X] I have made pertinent documentation changes
- [X] My changes do not introduce new warnings
- [X] I have written tests demonstrating that my changes are effective or that my feature works
- [X] Local unit tests pass with my changes
- [X] Any changes dependent on mine have been merged and published in downstream modules.
- [X] New documents have been locally validated with mkdocs

### CODE REVIEW

**Comment by danny-avila** [comment]
Nice job figuring this out!

**Comment by walbercardoso** [comment]
> Nice job figuring this out!

At the WrenchIcon file there is a rotate action, but seems its now working as expected. I can make a PR to refactor that and also the Retriever Icon, is you think its useful.

**Comment by danny-avila** [comment]
Yeah I do like that, would make it as a separate PR. Need to try this before merging

**Comment by danny-avila** [comment]
in your video and when I pulled it down, the animation looked off-center. the small change I made centers it better

**Comment by walbercardoso** [comment]
> Yeah I do like that, would make it as a separate PR. Need to try this before merging

Nice. Gonna make a PR tomorrow one for each animation. Thank you for merged this

**Pull request merged**
