### PR TITLE
Add localization support for endpoint pages components 

### PR DESCRIPTION
**Pull request by NoahDragon**
This change include two new features for localization:

1. Only Eng.tsx should be updated when modify existing string or add new ones. Other translation files do not need to be updated at the same time. Untranslated (not existing keys) string will be falled back to English phrases.
2. Allow localization strings accept dynmic values. For example: "use_two_things_together: use {0} and {1} together" where `{0}` `{1}` could be assigned values from a variable or hard coded string, then `localize(lang, 'use_two_things_together', 'bread', 'cheese')` would return "use bread and cheese together". In theory, you could put any number of `{/d}` placeholders to format the string, but please consider only use it when a string do not need to translate, like number, acronym, etc. Check the key `com_endpoint_default_with_num` for this feature usage in this PR.

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)
  

## How Has This Been Tested?

Build in Docker composer, and run an instance to test the changes.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by NoahDragon** [comment]
@danny-avila Could you please review this PR when you have a chance?

**Comment by danny-avila** [comment]
Looks good, but I can't tell if linter successfully ran. Can you confirm that you performed automatic linting/formatting with husky upon making commits?

**Comment by danny-avila** [comment]
change this file  .github\workflows\backend-review.yml line 8
`pull_request:` to `pull_request_target:`

**Comment by NoahDragon** [comment]
Thanks, just made the lint happy :)

**Comment by danny-avila** [comment]
> Thanks, just made the lint happy :)

awesome, thank you!

**Review by danny-avila — APPROVED** [review]

**Pull request merged**
