### PR TITLE
fix: Maximum Temperature for OpenAI endpoint set to 1 instead of 2 (which would result in gibberish output above a temperature 1)

### PR DESCRIPTION
**Pull request by marlonka**
## Summary

fix: I changed the maximum Temperature for OpenAI endpoint to 1 instead of 2 , because anything above 1 would result in gibberish output. See the OpenAI playground for example. There OpenAI sets the maximum temperature also to 1. 
Unexperienced users can set it to too high values without this fix resulting in unnecessary problems.

(Second idea would be to decrease steps from 0.01 to 0.1, since 0.01 steps is way to granular)

## Change Type

- [x] Bug fix (non-breaking change which fixes an issue)

## Testing
I build the docker container new and tested if the changes work well in front-end and correctly work with OpenAI endpoint by testing some messages. Its better now this way.

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.

### CODE REVIEW

**Comment by RedwindA** [comment]
It's better to implement it as a toggleable default option, hidden in the settings menu.

**Comment by danny-avila** [comment]
Thanks for the PR, but I'm not sure this is necessary. The API allows up to 2 and I would not like to intentionally limit it: https://platform.openai.com/docs/api-reference/chat/create#chat-create-temperature

**Comment by marlonka** [comment]
yeah okay, maybe there could be beginner and advanced settings in future in the ui

**Comment by RedwindA** [comment]
now it's 1😢😢

**Pull request closed without merging**
