### PR TITLE
Use react markdown as default, cleanup dependencies

### PR DESCRIPTION
**Pull request by HyunggyuJang**
Rather than, using custom markdown formatting, use ReactMarkdown consistently. 
Currently, only for the search result view, ReactMarkdown is used, for the other message views, custom TextWrapper is used with markdown-to-jsx.

@danny-avila, I'd like to know your thought about this! Is there any reason you prefer to use TextWrapper over ReactMarkdown?

### CODE REVIEW

**Comment by danny-avila** [comment]
Yes. All of the styling will change including the blinking cursor. I faced a lot of styling headaches with react-markdown that is mitigated with textwrapper. There will be issues with list items and code blocks as they are generated

**Comment by HyunggyuJang** [comment]
> Yes. All of the styling will change including the blinking cursor. I faced a lot of styling headaches with react-markdown that is mitigated with textwrapper. There will be issues with list items and code blocks as they are generated

Ah, got it, I fixed the blinking cursor, and from my side, it looks work well, could you try it in your free time?

**Comment by danny-avila** [comment]
> Ah, got it, I fixed the blinking cursor, and from my side, it looks work well, could you try it in your free time?

Sure thing. See if List items will give you issue, either numbered or bullet points, but I will test this out tonight

**Comment by HyunggyuJang** [comment]
> > Ah, got it, I fixed the blinking cursor, and from my side, it looks work well, could you try it in your free time?
> 
> Sure thing. See if List items will give you issue, either numbered or bullet points, but I will test this out tonight

Much appreciated. For me, both numbered and bullet points are rendered as expected.

**Comment by danny-avila** [comment]
@HyunggyuJang thanks again for your work

I'm all for this change if we can figure out why it seems to render output from sydney and chatgpt api differently

image

Something with the list content being wrapped with whitespace pre-wrap while for sydney its not. See the html below

**chatgpt**
```
<ol>
<li>
<span class="whitespace-pre-wrap mb-2">IBM Quantum Experience - a platform that allows users to run quantum circuits on real quantum hardware and simulators.</span>
</li>
<li>
<span class="whitespace-pre-wrap mb-2">Microsoft Quantum - a website that provides resources for learning about quantum computing and includes a quantum development kit for building quantum applications.</span>
</li>
<li>
<span class="whitespace-pre-wrap mb-2">QuTech Academy - an online resource for learning about quantum computing, including courses and tutorials.</span>
</li>
<li>
<span class="whitespace-pre-wrap mb-2">Quantum Computing Report - a website that covers news and developments in the field of quantum computing.</span>
</li>
<li>
<span class="whitespace-pre-wrap mb-2">Quantum Computing Stack Exchange - a community-driven Q&amp;A platform where you can ask and answer questions about quantum computing.</span>
</li>
<li>
<span class="whitespace-pre-wrap mb-2">MIT OpenCourseWare - offers free online courses that cover quantum computing and other related subjects.</span>
</li>
<li>
<span class="whitespace-pre-wrap mb-2">Quantum Magazine - a publication that features articles on the latest research in quantum computing and quantum physics.</span>
</li>
<li>
<span class="whitespace-pre-wrap mb-2">Quantum Computing for the Very Curious - a free online book that introduces the basics of quantum computing in a simple and accessible way.</span>
</li>
</ol>
```
**sydney**
```
<ul>
  <li>Free resources for learning about Quantum Computing<sup><a href="https://quantumzeitgeist.com/free-resources-for-learning-about-quantum-computing/" target="_new">1</a> </sup>: This website has a list of free online books, lectures, courses, and tutorials on quantum computing. You can learn the basics, the math, the algorithms, and the applications of quantum computing using Qiskit, a popular open-source framework for quantum programming.</li>
  <li>IBM Quantum Computing<sup><a href="https://www.ibm.com/topics/quantum-computing" target="_new">2</a> </sup>: IBM is one of the leaders in quantum computing research and development. They have a lot of information on their website about what quantum computing is, why we need it, how it works, and where it is used. They also have a platform where you can access real quantum systems and run your own quantum programs using Qiskit.</li>
  <li>Universal resources for quantum computing<sup><a href="https://learn.microsoft.com/en-us/azure/quantum/further-reading-qdk" target="_new">4</a> </sup>: This is a recent paper on arXiv that explores the role of various quantum resources in quantum computing tasks. It uses the framework of quantum resource theory to classify and quantify different types of quantum resources, such as entanglement, coherence, discord, magic, contextuality, etc. It also discusses how to manipulate and convert these resources using quantum operations.</li>
  <li>Quantum computing learning resources - Azure Quantum<sup><a href="https://learn.microsoft.com/en-us/azure/quantum/overview-azure-quantum" target="_new">5</a> </sup>: Microsoft also has a lot of quantum computing resources on their website. They have a Quantum Development Kit that lets you write quantum programs using Q#, a high-level quantum programming language. They also have Azure Quantum services that let you run your quantum programs on different types of quantum hardware and simulators.</li>
  <li>What is Azure Quantum?<sup><a href="https://www.ibm.com/quantum" target="_new">6</a> </sup>: This is a module from Microsoft Learn that gives you an overview of Azure Quantum, a cloud-based platform for quantum computing. It explains what Azure Quantum is, how it works, what it offers, and how to use it. It also covers some topics like resource estimation, optimization problems, and quantum machine learning.</li>
  </ul>
```

**Comment by danny-avila** [comment]
this might be really simple but it eluded me before i figured out how to get react-markdown to load html. since you've brought it up, i can take time to revisit if you don't get to it first.

**Comment by HyunggyuJang** [comment]
> @HyunggyuJang thanks again for your work
> 
> I'm all for this change if we can figure out why it seems to render output from sydney and chatgpt api differently
> 
> image
> 
> Something with the list content being wrapped with whitespace pre-wrap while for sydney its not. See the html below
> 
> **chatgpt**
> 
> ```
> <ol>
> <li>
> <span class="whitespace-pre-wrap mb-2">IBM Quantum Experience - a platform that allows users to run quantum circuits on real quantum hardware and simulators.</span>
> </li>
> <li>
> <span class="whitespace-pre-wrap mb-2">Microsoft Quantum - a website that provides resources for learning about quantum computing and includes a quantum development kit for building quantum applications.</span>
> </li>
> <li>
> <span class="whitespace-pre-wrap mb-2">QuTech Academy - an online resource for learning about quantum computing, including courses and tutorials.</span>
> </li>
> <li>
> <span class="whitespace-pre-wrap mb-2">Quantum Computing Report - a website that covers news and developments in the field of quantum computing.</span>
> </li>
> <li>
> <span class="whitespace-pre-wrap mb-2">Quantum Computing Stack Exchange - a community-driven Q&amp;A platform where you can ask and answer questions about quantum computing.</span>
> </li>
> <li>
> <span class="whitespace-pre-wrap mb-2">MIT OpenCourseWare - offers free online courses that cover quantum computing and other related subjects.</span>
> </li>
> <li>
> <span class="whitespace-pre-wrap mb-2">Quantum Magazine - a publication that features articles on the latest research in quantum computing and quantum physics.</span>
> </li>
> <li>
> <span class="whitespace-pre-wrap mb-2">Quantum Computing for the Very Curious - a free online book that introduces the basics of quantum computing in a simple and accessible way.</span>
> </li>
> </ol>
> ```
> 
> **sydney**
> 
> ```
> <ul>
>   <li>Free resources for learning about Quantum Computing<sup><a href="https://quantumzeitgeist.com/free-resources-for-learning-about-quantum-computing/" target="_new">1</a> </sup>: This website has a list of free online books, lectures, courses, and tutorials on quantum computing. You can learn the basics, the math, the algorithms, and the applications of quantum computing using Qiskit, a popular open-source framework for quantum programming.</li>
>   <li>IBM Quantum Computing<sup><a href="https://www.ibm.com/topics/quantum-computing" target="_new">2</a> </sup>: IBM is one of the leaders in quantum computing research and development. They have a lot of information on their website about what quantum computing is, why we need it, how it works, and where it is used. They also have a platform where you can access real quantum systems and run your own quantum programs using Qiskit.</li>
>   <li>Universal resources for quantum computing<sup><a href="https://learn.microsoft.com/en-us/azure/quantum/further-reading-qdk" target="_new">4</a> </sup>: This is a recent paper on arXiv that explores the role of various quantum resources in quantum computing tasks. It uses the framework of quantum resource theory to classify and quantify different types of quantum resources, such as entanglement, coherence, discord, magic, contextuality, etc. It also discusses how to manipulate and convert these resources using quantum operations.</li>
>   <li>Quantum computing learning resources - Azure Quantum<sup><a href="https://learn.microsoft.com/en-us/azure/quantum/overview-azure-quantum" target="_new">5</a> </sup>: Microsoft also has a lot of quantum computing resources on their website. They have a Quantum Development Kit that lets you write quantum programs using Q#, a high-level quantum programming language. They also have Azure Quantum services that let you run your quantum programs on different types of quantum hardware and simulators.</li>
>   <li>What is Azure Quantum?<sup><a href="https://www.ibm.com/quantum" target="_new">6</a> </sup>: This is a module from Microsoft Learn that gives you an overview of Azure Quantum, a cloud-based platform for quantum computing. It explains what Azure Quantum is, how it works, what it offers, and how to use it. It also covers some topics like resource estimation, optimization problems, and quantum machine learning.</li>
>   </ul>
> ```

Ah, didn't test in ChatGPT side, thanks for your test. 

> this might be really simple but it eluded me before i figured out how to get react-markdown to load html. since you've brought it up, i can take time to revisit if you don't get to it first.

Yes, please go ahead. Thanks a lot.

**Comment by HyunggyuJang** [comment]
Hey, @danny-avila, I think the difference comes from GFM plugin, without remarkGfm plugin enabled, each list item is wrapped by `p`, treating it as a paragraph. But with GFM plugin, each list item doesn't get wrapped.

By default, GFM plugin is on for the Content component, so I'm not sure why you get mangled view of list items. 

image
Even for the ChatGPT browser version seems work fine.

**Comment by danny-avila** [comment]
Good catch. I’ll work on debugging that on my end

**Comment by danny-avila** [comment]
Interesting. I did a clean install on a new computer and no issues. I might've been working off an old client bundle 🤷 

Looks good, this should run messages faster overall

**Review by danny-avila — APPROVED** [review]

**Pull request merged**
