### PR TITLE
♻️ refactor: Login and Registration component Improvement

### PR DESCRIPTION
**Pull request by ohneda**
## Summary

I've made some improvements to the `Login` and `Registration` components.

1. Previously, the `Login` and `Registration` displayed a blank screen while fetching `StartupConfig` data from the API. I've added a blinking logo that appears while the forms wait for the API to return the`StartupConfig` data. No worries, if you don't like this effect, you can simply remove the BlinkAnimation wrapper.

https://github.com/danny-avila/LibreChat/assets/283038/cc1f6e98-8a47-475f-a196-c3a5f57d40a7

2. I've also implemented error messaging to inform users whenever they fail to access the API during the login or registration processes.

<kbd>image</kdb>

3. Additionally, I've optimized the `Login` component only to make one API call for StartupConfig, even if the component re-renders after a failed login attempt.
4. Previously, if a user failed to log in, then successfully logged in, and then logged out, the error message would still be displayed. I've made sure that the error message is cleared after a successful login.
5. I've refactored the code to reduce duplication between the login and registration components.

I initially planned to make just a small improvement, but it turned into a bit of a larger change. However, the functionality of the `Login` and `Registration` components remains the same. 

Please let me know if you have any concerns. I hope these changes can help improve the user experience, even if just a little bit. 

## Change Type

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] My changes do not introduce new warnings
- [x] Local unit tests pass with my changes

### CODE REVIEW

**Comment by danny-avila** [comment]
@ohneda can you make me a contributor? I made some changes so we can optimize this a bit further. If you add me, I can avoid closing this PR and pushing to your branch.

Also could use your help on aligning request/reset password pages with the changes I made, which will make sense once you see them

**Comment by ohneda** [comment]
@danny-avila Thanks, I have added you as a contributor to my repository.

**Comment by ohneda** [comment]
Thanks for letting me know. All my PR are not urgent, so no need to rush

**Comment by danny-avila** [comment]
@ohneda my changes are all wrapped up, can you confirm it's all working as intended on your end?

**Comment by ohneda** [comment]
@danny-avila  Thanks, Everything is working as intended and it's become more clear! I see that the request/reset password pages have been updated too. Is there anything else I need to work on?

**Comment by danny-avila** [comment]
> @danny-avila Thanks, Everything is working as intended and it's become more clear! I see that the request/reset password pages have been updated too. Is there anything else I need to work on?

Thanks for checking!

**Comment by danny-avila** [comment]
@mkagit you need to edit the index.html file.

It is being followed as much as the browser API allow---what you want requires a hardcoded change.

**Comment by mkagit** [comment]
Even after editing the index.html and doing local building it's working **except** for the title at the login registration website page.
It is a issue because the title keep changing between the env title and Librechat title when reloading. 
Then I thought you were working about it in that branch.

**Comment by danny-avila** [comment]
> @danny-avila even after editing the index.html and doing local building it's working **except** for the title at the login registration website page. It is a issue because the title keep changing between the env title and Librechat title when reloading. Then I thought you were working about it in that branch.

perhaps you need to change this file too: client/vite.config.ts

**Comment by mkagit** [comment]
@danny-avila edited the client index.html, vite.config.ts manifest and the behavior is still there. It keeps changing between the new title and Librechat title in the website title when reloading the login page.

**Comment by mkagit** [comment]
@danny-avila using here the help from sonnet, it's pointing to the useEffect callback in the startup.tsx and I'm looking now also in the payload router in the config.ts. Is going from undefined to the fallback. Is it make any sense?

Don't know if it could be related but my login envs is like that:
  ALLOW_EMAIL_LOGIN = 'true'
  ALLOW_PASSWORD_RESET = 'false'
  ALLOW_REGISTRATION = 'false'
  ALLOW_SOCIAL_LOGIN = 'false'
  ALLOW_SOCIAL_REGISTRATION = 'false'
  ALLOW_UNVERIFIED_EMAIL_LOGIN = 'true'
  APP_TITLE = 'MyChat'

**Pull request merged**
