### PR TITLE
🔖 fix: bookmark error using CosmosDB - Added `index` to position field in schema

### PR DESCRIPTION
**Pull request by bijucyborg**
…gSchema.js

# Pull Request Template

⚠️ Before Submitting a PR, Please Review:
- Please ensure that you have thoroughly read and understood the [Contributing Docs](https://github.com/danny-avila/LibreChat/blob/main/.github/CONTRIBUTING.md) before submitting your Pull Request.

⚠️ Documentation Updates Notice:
- Kindly note that documentation updates are managed in this repository: [librechat.ai](https://github.com/LibreChat-AI/librechat.ai)

## Summary

LibreChat installation on Azure and using CosmosDB serverless instance in lieu of MongoDB.

The bookmark feature does not seem to work though and i see the following error in the logs.

2024-09-29T17:25:39.736037227Z 2024-09-29 17:25:39 �[31merror�[39m: �[31m[createConversationTag] Error creating conversation tag Error=2, Details='Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 4e6656ff-48c9-4f91-ba59-f6a35cf7eb08; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 4e6656ff-48c9-4f91-ba59-f6a35cf7eb08; Reason: (Response status code does not indicate success: BadRequest (400); Substatus: 0; ActivityId: 4e6656ff-48c9-4f91-ba59-f6a35cf7eb08; Reason: (Message: {"Errors":["The index path corresponding to the specified order-by item is excluded."]}

On the UI I just get a message in red saying "There was an error creating the bookmark"

## Change Type

Please delete any irrelevant options.

- [X ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Translation update

## Testing

- Deploy LibreChat on Microsoft Azure with CosmosDB
- With current code you will not be able to create bookmarks, one observes error in log regarding createConversationTag
- Adding index to position field in conversationTagSchema.js solves the problem
- Create image with modified code
- Deploy on Azure
- Check creating and deleting bookmarks.

## Checklist

Please delete any irrelevant options.

- [ x] My code adheres to this project's style guidelines
- [ x] I have performed a self-review of my own code
- [x ] I have commented in any complex areas of my code
- [ ] I have made pertinent documentation changes
- [x ] My changes do not introduce new warnings
- [ ] I have written tests demonstrating that my changes are effective or that my feature works
- [ ] Local unit tests pass with my changes
- [ ] Any changes dependent on mine have been merged and published in downstream modules.
- [ ] A pull request for updating the documentation has been submitted.

### CODE REVIEW

**Review by danny-avila — APPROVED** [review]

**Comment by danny-avila** [comment]
great thank you, but Im curious, everything else is working with CosmosDB?

**Comment by maxesse** [comment]
How weird, I am also using Azure CosmosDB for MongoDB and it works 100% ok, including bookmarks, before this PR.

**Comment by bijucyborg** [comment]
yes everything else seems to 

> How weird, I am also using Azure CosmosDB for MongoDB and it works 100% ok, including bookmarks, before this PR.

strange then I was continuously getting errors about conversation ids and creating bookmarks isn't possible.
Screenshot 2024-10-01 at 16 26 40

Another user has reported the same issue. See discussion board
https://github.com/danny-avila/LibreChat/discussions/4278

Could it be a performance issue? I had this issue on two installations with the latest docker image.
One was serverless and on the other I had restricted the RU's per collection to 400.

**Comment by maxesse** [comment]
Wait, are you using CosmosDB for MongoDB, or just CosmosDB? I am using CosmosDB for MongoDB, literally worked out of the box, without having to change anything.

**Comment by maxesse** [comment]
Yes I have TITLE_CONVO, I don't think it's that. I am using the vCore version of Cosmos - I seem to remember I also had issues when initially deploying it, using vCore made it work - I don't remember the details as it was a while ago, but I think I was also getting tons of errors. 
image

**Comment by proschowsky** [comment]
We are using Librechat with *Azure Cosmos DB for MongoDB account (RU)* and had the same issue related to bookmarks.

We also had issues related to social logins, since the database does not support sparse indexes.  We are only using OpenID, so we solved it by deleting the indexes for the other social login providers. Otherwise it is working fine.

**Comment by maxesse** [comment]
While the RU version of Cosmos is enticing because of horizontal scalability etc I didn't really wanna deploy it in production with an unsupported/untested backend db, as there might be more issues cropping up (also going forward, as Danny is not testing against it). Hence why I went with vCore which is exactly like running a local Mongo instance and everything works as expected. I can still scale easily to more capacity although it's not 'elastic'.

**Comment by bijucyborg** [comment]
Thanks @maxesse and @proschowsky 
ok so these are indeed issues related to performance. my issue with provisioning vcores on cosmosdb is the cost, If I provision 2vcore burstable or 2vcore full its $145 or $209 per month respectively. Unless I have a number of users this will not be justifiable. At least for now adding an index to position field in ConversationTag schema solves my problem. 
I have now a fully functional Librechat running for 4 euros a day on Azure and I plan to bring it down even lower :) Comos is now running for free and the cost is coming from the azure postgresql flexible server (for RAG) which is costing 2 eur and load balancer 1 eur per day.

**Comment by maxesse** [comment]
You don't wanna see how much my deployment costs 🫣. It's got azure container apps with autoscaling for the frontend, cosmos vCore (which is 200 a month and I haven't even enabled high availability yet), application gateway which is another 300 a month to terminate the frontend ip and provide OWASP mitigation and blocking bots, Postgres flexible server like yours, redis so that the frontend can scale otherwise you get session issues, and I'll probably end up having to add litellm and a really beefy gpu server for llmguard as our privacy people want to 'block HR topics' but without going into the details of what specifically so it needs a trained model in between to do that job and add latency. So far it costs about 1k a month but I predict it'll be more in the 3k once we add all this stuff and other custom web services also using models to retrieve live data and serve it to librechat tools.

**Pull request merged**
