### PR TITLE
🔧 style(fix): Convo Title Fade Effect

### PR DESCRIPTION
**Pull request by walbercardoso**
## Summary

I believe that in one of the last merges the fade effect in the convo title was removed. Returning to the previous UI design.

Before:

image

image

After:
image

image

## Change Type

Please delete any irrelevant options.

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist

Please delete any irrelevant options.

- [X] My code adheres to this project's style guidelines
- [X] I have performed a self-review of my own code
- [X] I have commented in any complex areas of my code
- [X] I have made pertinent documentation changes
- [X] My changes do not introduce new warnings
- [X] I have written tests demonstrating that my changes are effective or that my feature works
- [X] Local unit tests pass with my changes
- [X] Any changes dependent on mine have been merged and published in downstream modules.
- [X] New documents have been locally validated with mkdocs

### CODE REVIEW

**Comment by danny-avila** [comment]
Thanks for spotting this. Looks like you need to remove the deletion of `.env.example` or else it will merge the deletion to the repo.

**Review by danny-avila — COMMENTED** [review]
Remove the .env.example deletion

**Review by danny-avila — CHANGES_REQUESTED** [review]
Remove the .env.example deletion as previously stated. Thanks!

**Comment by walbercardoso** [comment]
> Thanks for spotting this. Looks like you need to remove the deletion of `.env.example` or else it will merge the deletion to the repo.

Thank you Danny. I already removed the deletion of .env.example

**Review by danny-avila — APPROVED** [review]

**Comment by danny-avila** [comment]
@walbercardoso I had to revert this commit due to Icons shifting when active, see https://github.com/danny-avila/LibreChat/pull/2117

**Pull request merged**
