### PR TITLE
Bind librechat config file in the docker-compose

### PR DESCRIPTION
**Pull request by anatoliykmetyuk**
# Pull Request Template

## Summary

By default the librechat.yaml was not bound to the proper location, so my setup was erroring that it couldn't find this file.

## Change Type

Please delete any irrelevant options.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist

Please delete any irrelevant options.

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.
- [x] New documents have been locally validated with mkdocs

### CODE REVIEW

**Comment by kedar-1** [comment]
You need to bind a librechat.yaml in docker-compose.override. 
See [https://github.com/danny-avila/LibreChat/blob/main/docker-compose.override.yml.example ](https://github.com/danny-avila/LibreChat/blob/main/docker-compose.override.yml.example )
IMO it's a little weird but the deployment works like this.

**Comment by danny-avila** [comment]
The reason for this to not make the librechat.yaml file a required step for spinning up the default compose file. Otherwise, if no file is present, there will be an error.

**Comment by anatoliykmetyuk** [comment]
> The reason for this to not make the librechat.yaml file a required step for spinning up the default compose file. Otherwise, if no file is present, there will be an error.

It would be good to have this documented somewhere. The docs for the config file do not mention where to mount it, and it took me like 30 minutes to figure out. Also I'm not using the compose override file since I deploy via Dockge (https://github.com/louislam/dockge) and I believe it doesn't support them.

**Comment by fuegovic** [comment]
> (...) Also I'm not using the compose override file since I deploy via Dockge (https://github.com/louislam/dockge) and I believe it doesn't support them.

I'm using portainer, and to make my config file management easier I host it on GitHub and use the env var `CONFIG_PATH` to provide the URL that point to the raw file

**Comment by danny-avila** [comment]
> > The reason for this to not make the librechat.yaml file a required step for spinning up the default compose file. Otherwise, if no file is present, there will be an error.
> 
> It would be good to have this documented somewhere. The docs for the config file do not mention where to mount it, and it took me like 30 minutes to figure out. Also I'm not using the compose override file since I deploy via Dockge (https://github.com/louislam/dockge) and I believe it doesn't support them.

It’s in the docs, it shows how to bind it via override file, which can be applied like you did in the PR. I do think we could be clearer about the CONFIG_PATH option especially the http request option

**Pull request closed without merging**
