### PR TITLE
Feat email password reset

### PR DESCRIPTION
**Pull request by danorlando**
Adds password reset email functionality.

## Type of change

Please delete options that are not relevant.

- [X] New feature (non-breaking change which adds functionality)

## How Has This Been Tested?

Used [this article](https://miracleio.me/snippets/use-gmail-with-nodemailer/) to configure my gmail account to be able to send emails from the app from it. Once that is done, just set the .env vars accordingly and run password reset request.

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by Berry-13** [comment]
This is absolutely fantastic!🎉

**Comment by danorlando** [comment]
Setting this back to draft. There's a couple things I think I can make cleaner.

**Review by fuegovic — APPROVED** [review]
I tested both from local and hosted, the feature is working!

the only thing that wasn't working in my tests is the `EMAIL_FROM=` that gmail wouldn't apply 

The set up was easier than expected and the password reset worked flawlessly 
- I was able to reset the password once with the emailed link
- I got a message telling me to refill the form to get another reset link when trying to use the same link a second time

👍

**Comment by danny-avila** [comment]
Thanks so much for this!

Seems a little off that the package-lock file got reduced by 26k lines.

For future reference, it's safe to rebuild the package-lock file when you delete and run `node config\packages.js`

I'll update this script so that it deletes the file for you, and will add it to root package.json

**Pull request merged**
