### PR TITLE
🔧 fix: Delete Archived Chat z-index issue

### PR DESCRIPTION
**Pull request by arthurian**
## Summary

This PR fixes a UI issue in **Settings > General > Archived Chats > Manage** where users can't delete an archived chat because the **Delete chat?** dialog is hidden. The problem is that the z-order was changed at some point, causing the **Delete chat?** dialog to be stacked behind the **Archived chats** table (z-index 50 < 999). 

This PR updates the `z-index` on the dialog so that the ordering is as follows:

1. **Settings**: `z-index: auto`
2. **Archived chats**: `z-index: 999`
3. **Delete chat?**: `z-index: 1000` changed from `z-index: 50`

## Change Type

- [x] Bug fix (non-breaking change which fixes an issue)

## Testing

I tested these changes locally and verified the z-order in the browser using standard devtools. Screenshots included below for reference.

**Before the change:**

librechat-delete-archived-chat-issue

**After the change:**

librechat-delete-archived-chat-fix

### **Test Configuration**:

No special configuration required to test, just create a conversation, archive it, and then attempt to delete it.

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] My changes do not introduce new warnings

### CODE REVIEW

**Comment by danny-avila** [comment]
@berry-13 can you specify which branch? Fixes like this should be scoped like this PR

**Comment by arthurian** [comment]
FYI resolved the conflicts introduced by PRs merged before this one, so this branch is mergeable again. 

I'm not sure if @berry-13's bigger branch makes the z-index fix obsolete or not. FWIW I did search the issues and open PRs to see if anyone was working on this issue, so I think that's another good reason to more tightly scope PRs moving forward. It helps the rest of us know if an issue is known and being worked on.

**Comment by danny-avila** [comment]
thanks, agreed!

**Comment by berry-13** [comment]
@arthurian hey, sorry I missed replying to both you and Danny. Can you let me know which browser you were using for the test? The OGDialog shouldn't have this issue

**Comment by arthurian** [comment]
I was using the Chrome browser for testing if that helps.

**Pull request merged**
