### PR TITLE
🚀 feat: o1

### LINKED ISSUE #4018: Enhancement: support o1-preview, o1-mini
### What features would you like to see added?

support OpenAI o1-preview, o1-mini

### More details

The o1-preview and o1-mini do not support streaming output and system prompts, therefore they cannot be used.

### Which components are impacted by your request?

General

### Pictures

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by danny-avila**
## Summary

- Added o1 models to the default OpenAI models list, ensuring they are available for selection.
- Implemented special handling for o1 models with custom instructions, adjusting how prompts are constructed.
- Updated token cost calculations to account for the complexity of o1 models, including separate tracking for reasoning tokens.
- Refactored the BaseClient to use new input/output token keys, improving flexibility across different model types.
- Updated the MessageEndpointIcon component to differentiate the OpenAI icon color for o1 models, providing visual distinction.
- Updated localization to include new error messages related to o1 models and system message support.
- Adjusted the getResponseSender function to return 'o1' as the default sender string for o1 models.

### Other Changes
- Added a new error type for models that don't support system messages, improving error handling and user feedback.
- Enhanced the AnthropicClient to use the new input/output token keys and added prompt caching support for claude-3-opus.

Testing:

1. Verify that o1 models appear in the model selection list.
2. Test conversations with o1 models, ensuring that custom instructions are handled correctly.
3. Check that token usage is accurately calculated and displayed for o1 models.
4. Confirm that the MessageEndpointIcon displays the correct color for o1 models.
5. Test error scenarios, particularly when attempting to use system messages with unsupported models.
6. Verify that the correct sender string is displayed for o1 model responses.

### CODE REVIEW

**Comment by kukoboris** [comment]
@danny-avila I have updated LibreChat (deploy-compose) but there are no o1 models in the model selection list....

**Comment by TyraVex** [comment]
> @danny-avila I have updated LibreChat (deploy-compose) but there are no o1 models in the model selection list....

You need to be API tier 5:
https://platform.openai.com/settings/organization/limits

And if you do:
https://community.openai.com/t/were-tier-5-usage-but-dont-have-access-to-o1-models/937904/3
"""
OpenAI confirmed that we should have access this afternoon, Pacific time.
"""

**Comment by kneelesh48** [comment]
Do these changes work with o1-preview on openrouter?

**Comment by fuegovic** [comment]
> Do these changes work with o1-preview on openrouter?

OpenRouter o1 also works!
image

**Pull request merged**
