### PR TITLE
feat: German translations

### PR DESCRIPTION
**Pull request by XHyperDEVX**
# Pull Request Template

### ⚠️ Pre-Submission Steps:

1. Before starting work, make sure your main branch has the latest commits with `npm run update`
2. Run linting command to find errors: `npm run lint`. Alternatively, ensure husky pre-commit checks are functioning.
3. After your changes, reinstall packages in your current branch using `npm run reinstall` and ensure everything still works. 
    - Restart the ESLint server ("ESLint: Restart ESLint Server" in VS Code command bar) and your IDE after reinstalling or updating.
4. Clear web app localStorage and cookies before and after changes.
5. For frontend changes:
    - Install typescript globally: `npm i -g typescript`.
    - Compile typescript before and after changes to check for introduced errors: `tsc --noEmit`.
6. Run tests locally:
    - Backend unit tests: `npm run test:api`
    - Frontend unit tests: `npm run test:client`
    - Integration tests: `npm run e2e` (requires playwright installed, `npx install playwright`)

## Summary

Please provide a brief summary of your changes and the related issue. Include any motivation and context that is relevant to your changes. If there are any dependencies necessary for your changes, please list them here.

## Change Type

Please delete any irrelevant options.

- [x] Translation support
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation update 

## Testing

Please describe your test process and include instructions so that we can reproduce your test. If there are any important variables for your testing configuration, list them here.

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.

### CODE REVIEW

**Review by berry-13 — COMMENTED** [review]
It would be better if you put it after all the others.

Like this: 


en
cn
it
br
es
de

**Review by berry-13 — COMMENTED** [review]
you should remove this from the German file:

com_nav_lang_english: 'Englisch',
    com_nav_lang_chinese: '中文 [Chinesisch]',
    com_nav_lang_italian: 'Italienisch',
    com_nav_lang_brazilian_portuguese: 'Portugiesisch/Brasilianisch',
    com_nav_lang_spanish: 'Spanisch',

and instead put this in English

com_nav_lang_german: 'the-word-German-in-German ',

I hope I've explained

**Comment by danorlando** [comment]
How are you doing these translations? I ask because I recently ran into a situation where I needed to add some resource strings and I had to manually google translate each one in each language one-by-one, which felt very tedious.

**Comment by XHyperDEVX** [comment]
> How are you doing these translations? I ask because I recently ran into a situation where I needed to add some resource strings and I had to manually google translate each one in each language one-by-one, which felt very tedious.

I am a German native speaker and understand English quite well. Not perfect, but it's enough, and when it doesn't I put the English sentence into the translator and then formulate my own German sentence from it. Copy paste from the translator is stupid.

But in short: I am a German native speaker.

**Comment by fuegovic** [comment]
> It would be better if you put it after all the others.
> 
> Like this:
> 
> en cn it br es de

@Berry-13 Shouldn't the language list be alphabetical tho? With 5 languages it doesn't really matter but if we end up with a lot, having them in the contribution order will be confusing

**Pull request merged**
