### PR TITLE
Make sydney tone adjustable during conversation

### PR DESCRIPTION
**Pull request by HyunggyuJang**
Is a follow-up of #128.

### CODE REVIEW

**Comment by danny-avila** [comment]
Hey, thanks for this! I didn't get around to it as I've been reviewing 2 big PRs, 1 merged now, and making live fixes to main. I'll be out tomorrow but back at it Saturday. You may want to see how the latest updates affected it too

**Comment by HyunggyuJang** [comment]
> Hey, thanks for this! I didn't get around to it as I've been reviewing 2 big PRs, 1 merged now, and making live fixes to main. I'll be out tomorrow but back at it Saturday. You may want to see how the latest updates affected it too

Thanks for your sincere response! I always learn a lot from you and active contributors. They are superb, I’ll also learn by digesting the recent big, precious commits made to main!

**Comment by HyunggyuJang** [comment]
@danny-avila I updated based upon the main branch! Please review.

**Comment by danny-avila** [comment]
Thanks for this! Looks good, I'll be changing the icon to match the 'advanced mode' one, since yours seems to render too small

**Pull request merged**
