### PR TITLE
🅰️ feat: Azure Config to Allow Different Deployments per Model

### LINKED ISSUE #1390: Enhancement: Azure OpenAI: Enhance Configuration to Allow Multiple Deployments & Alternative Model Names
### What features would you like to see added?

In https://github.com/danny-avila/LibreChat/pull/1389, and after finally acquiring my own Azure OpenAI access, I've learned that we can effectively reduce all confusion surrounding Azure OpenAI configuration with a singular setup file.

Something like a YAML config file would allow handling of all possible deployment configurations easily and without confusion.

### More details

This is planned, creating an issue for tracking

### Which components are impacted by your request?

_No response_

### Pictures

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### LINKED ISSUE #1800: Enhancement: allow private URL for Azure API
### What features would you like to see added?

Some of the companies, do not expose the Azure OpenAI API directly for their empoyees, but they put it behind some pass-through proxy. E.g. instead of connecting to:

`https://myCompanyInstance.openai.azure.com/openai/deployments/${azureOpenAIApiDeploymentName}`

We're connecting to:

`https://my-company.dev.ai.internal.domain.xxx/passthrough/openai/deployments/${azureOpenAIApiDeploymentName}`

That way, the company can work off of one Azure API key, but provide their internal tokens for usage tracking etc.

Currently, I need to manually patch the [azureUtils.js](https://github.com/danny-avila/LibreChat/blob/main/api/utils/azureUtils.js) to make LibreChat work properly. If such workflow would become a first-class citizen of LibreChat, it would be great!

### More details

As a bonus, the above private pass-through address usually needs private CA to be present in the system to validate the company's SSL - would be great to make it possible to mount a `.pem` file into the deployment to be used as `NODE_EXTRA_CA_CERTS`

### Which components are impacted by your request?

_No response_

### Pictures

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by danny-avila**
## Summary

Closes #1390 
Closes #1800

The most seamless way to integrate this was by "deprecating" almost every Azure env. variable to prefer the `librechat.yaml` configuration.

```.env
# updated .env.example

# Note: these variables are DEPRECATED
# Use the `librechat.yaml` configuration for `azureOpenAI` instead
# You may also continue to use them if you opt out of using the `librechat.yaml` configuration

# AZURE_OPENAI_DEFAULT_MODEL=gpt-3.5-turbo # Deprecated
# AZURE_OPENAI_MODELS=gpt-3.5-turbo,gpt-4 # Deprecated
# AZURE_USE_MODEL_AS_DEPLOYMENT_NAME=TRUE # Deprecated
# AZURE_API_KEY= # Deprecated
# AZURE_OPENAI_API_INSTANCE_NAME= # Deprecated
# AZURE_OPENAI_API_DEPLOYMENT_NAME= # Deprecated
# AZURE_OPENAI_API_VERSION= # Deprecated
# AZURE_OPENAI_API_COMPLETIONS_DEPLOYMENT_NAME= # Deprecated
# AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME= # Deprecated
# PLUGINS_USE_AZURE= # Deprecated
```

They can still be used as I've left their logic completely untouched. When configuring them via the config file, though, you will get warnings for using them:

```bash
2024-02-21 12:44:00 warn: The `AZURE_API_KEY` environment variable (related to setting a single Azure API key) should not be used in combination with the `azureOpenAI` endpoint configuration, as you will experience conflicts and errors.
# .. and so on
```

### The benefit:
image

**I am seamlessly using 2 different deployments on different regions with this configuration in the upcoming update:**

```yaml
endpoints:
  azureOpenAI:
    groups:
    - group: "my-westus-region-group-name"
      apiKey: "${WESTUS_API_KEY}"
      instanceName: "my-westus-region"
      version: "2023-12-01-preview"
      # baseURL: https://prod.example.com
      # additionalHeaders:
      #   X-Custom-Header: value
      models:
        gpt-4-vision-preview:
          deploymentName: gpt-4-vision-preview
          version: "2024-02-15-preview"
        gpt-3.5-turbo:
          deploymentName: gpt-35-turbo
        gpt-3.5-turbo-1106:
          deploymentName: gpt-35-turbo-1106
        gpt-4:
          deploymentName: gpt-4
        gpt-4-1106-preview:
          deploymentName: gpt-4-1106-preview
    - group: "my-eastus-region-group-name"
      apiKey: "${EASTUS_API_KEY}"
      instanceName: "my-eastus-region"
      deploymentName: gpt-4-turbo
      version: "2024-02-15-preview"
      models:
        gpt-4-turbo: true
```

Group names are arbitrary. The `models` listed must conform to known OpenAI models. Naming groups by region/instance is not necessary and is just convention for grouping. Duplicate group and model names are not allowed.

Note how I defined my own API key environment variables. You can define custom environment variables for instanceName, deploymentName, version, and apiKey fields, provided you use the following format: `${MY_ENV_VAR}`.

In my second group, "my-eastus-region-group-name", `gpt-4-turbo` has no defined deploymentName or version and is set to `true`. In this case, it bubbles up and uses the group's deploymentName and version. If it had one of these fields, it would use the group's field for whichever is missing.

## Change Type

- [x] New feature (non-breaking change which adds functionality)
- [x] Documentation update

## Testing

Added new tests extensively testing configuration done through `librechat.yaml` file. The server will crash on startup if not configured correctly.

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.

### CODE REVIEW

**Comment by tkd510** [comment]
How should the following two parameters be set in librechat.yaml?
- AZURE_OPENAI_API_EMBEDDINGS_DEPLOYMENT_NAME
- PLUGINS_USE_AZURE

We are now able to switch the Azure model, but the Plugins disappeared.

**Comment by tkd510** [comment]
I set it up as follows, but the plugins did not activate:

  azureOpenAI:
    groups:
      - group: "my-region-group"
        apiKey: "myAPIKEY"
        instanceName: "myinstanceName"
        version: "2024-02-15-preview"
        # baseURL:https://prod.example.com
        # additionalHeaders:
        #   X-Custom-Header: value
        models:
          gpt-3.5-turbo-1106:
            deploymentName: gpt-35-turbo-1106
          gpt-4-1106-preview:
            deploymentName: gpt-4-1106-preview
          gpt-4-vision-preview:
            deploymentName: gpt-4-vision-preview
        plugins: true
        titleConvo: true

**Comment by danny-avila** [comment]
> plugins: true

this looks right. Make sure the indentation is correct. plugins should be at the same level as `groups`.

granted if you are checking out the PR branch make sure you’re installing correctly.

Will wrap up documentation tomorrow for clarity

**Comment by tkd510** [comment]
Thank you. The plugins and convo have been modified to work with the changed indents. We are currently checking if the Azure model is switchable in the plugins.

**Comment by tkd510** [comment]
It is a browser plugin that was using OPENAI and has been changed to AZURE as shown below. If the changes are reverted, an API key will be requested when the plugin is installed. It has been confirmed to work by setting environment variables in the .env file.

mainfest.json
  {
    "name": "Browser",
    "pluginKey": "web-browser",
    "description": "Scrape and summarize webpage data",
    "icon": "/assets/web-browser.svg",
    "authConfig": [
      {
        "authField": "AZURE_API_KEY",
        "label": "OpenAI API Key",
        "description": "Browser makes use of OpenAI embeddings"
      }
    ]
  },

**Comment by danny-avila** [comment]
> Incredible 🤩 Do I get it right that instance_name is hardcoded into `librechat.yaml` now? This can be tricky when deploying models via Terraform. But nevertheless, I will figure my way around it.

Thanks, about to merge this. no you can use environment variables, you specify the env variables to use through the config file

**Pull request merged**
