### PR TITLE
🧠 feat: Prompt caching switch, prompt query params; refactor: static cache, prompt/markdown styling, trim copied code, switch new chat to convo URL

### PR DESCRIPTION
**Pull request by danny-avila**
## Summary

- Implemented a UI switch for Anthropic prompt caching, allowing users to toggle this feature on and off.
- Added support for query parameters to pre-fill the chat input, improving integration possibilities.
- Refactored the role update system to handle multiple permission types simultaneously, enhancing flexibility and reducing database operations.
- Updated the static cache configuration to use a more reasonable one-day time frame for better performance and freshness balance.
- Improved styling for prompt cards and nested lists, enhancing readability and visual appeal.
- Fixed issues with streaming response cursor in nested lists and lists with code blocks (regression, https://github.com/danny-avila/LibreChat/pull/3777)
- Copying code now no longer has newlines
- When a new chat is finalized, the conversation URL switches from `/c/new` to `/c/${UUID}`

**More details:**
- Added a new `promptCache` option to the Anthropic client and settings UI.
- Implemented `useQueryParams` hook to handle URL query parameters for pre-filling chat input.
- Refactored `updateAccessPermissions` function to handle multiple permission types in a single operation.
- Updated static cache configuration for `sMaxAge` and `maxAge` to 1 day and 2 days instead of 1 week and 4 weeks respectively.
- Improved styling for prompt cards, including better handling of long text and nested lists.
- Implemented a streaming cursor for better visual feedback during message generation.
- Added unit tests for the new role update system and other components.
- `copy-to-clipboard` includes a newline by default. For code blocks, this was changed to trim the output to avoid including extraneous newlines
- the `finalHandler` now sets the URL according to the conversationId upon successful completion.

## Change Type

- [x] New feature (non-breaking change which adds functionality)
**- [ ] TODO: This change requires a documentation update**

https://github.com/LibreChat-AI/librechat.ai/issues/110
https://github.com/LibreChat-AI/librechat.ai/issues/109

## Testing

To test these changes:

1. Start the application and navigate to the Anthropic settings.
2. Verify that the new "Use Prompt Caching" switch is present and functional.
3. Test the query parameter functionality by appending `?prompt=Hello%20World` to the URL and checking if the chat input is pre-filled.
4. Verify that the streaming cursor appears and behaves correctly during message generation.
5. Check the styling of prompt cards and nested lists for improved readability.
6. Copy code, observe no newlines
7. Observe UUID in URL after conversation finalizes

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.

### CODE REVIEW

**Comment by danny-avila** [comment]
> @danny-avila And no URL according to the conversationId upon successful completion
> изображение

There's a static cache your instance might be using. 

Try setting these values to 0 and trying again

https://www.librechat.ai/docs/configuration/dotenv#static-file-handling

**Comment by kukoboris** [comment]
@danny-avila For now I start using docker-compose.yml instead of deploy-compose.yml. It uses librechat-dev:latest and it works for me

**Comment by danny-avila** [comment]
> @danny-avila For now I start using docker-compose.yml instead of deploy-compose.yml. It uses librechat-dev:latest and it works for me

thanks for letting me know, seeing some weird behavior on that build again, investigating

**Comment by ThomasBaruzier** [comment]
Thanks for this PR!

Does the cache feature work when regenerating messages? Is it able to use the cache up to the latest similar token between the cache and a new request? Or does it need to be rebuilt from the first message each time a token is edited, whatever its position?

I would like to know if it would be more cost-efficient to edit or regenerate the last messages or to continue a conversation without touching any token, even if the responses are mediocre.

**Comment by danny-avila** [comment]
> Thanks for this PR!
> 
> Does the cache feature work when regenerating messages? Is it able to use the cache up to the latest similar token between the cache and a new request? Or does it need to be rebuilt from the first message each time a token is edited, whatever its position?
> 
> I would like to know if it would be more cost-efficient to edit or regenerate the last messages or to continue a conversation without touching any token, even if the responses are mediocre.

@ThomasBaruzier Honestly, I'm not sure.

The best way to find out is to try it. If you care to dig into it, and even publicizing your research, I'd be happy to share it on our blog.

I will also try to find out for you. If you check the debug logs, and analyze the spend logs, you are sure to find out. 

```bash
2024-08-27T14:18:41.159Z debug: [spendStructuredTokens] conversationId: e3724a12-0115-48c4-a37a-a7b173546921 | Context: message | Token usage:
{
    promptTokens.input: 8,
    promptTokens.write: 2658,
    promptTokens.read: 0,
  completionTokens: 30,
}
```

Also, it's worth looking at the Transactions collection in the database.

**Comment by ThomasBaruzier** [comment]
> @ThomasBaruzier Honestly, I'm not sure.
> 
> The best way to find out is to try it. If you care to dig into it, and even publicizing your research, I'd be happy to share it on our blog.

I did not perform any scientific approach, but their caching feature is definitely not smart.
For the last two weeks, my daily usage did 10 to 20% of cache hit because I tend to regenerate quite aggressively.
Forcing myself to continue the conversation for over 50-75k tokens today bumped my cache hit to 50 to 60% in September.

I'll update this comment when if I do proper testing

**Pull request merged**
