### PR TITLE
🔧 fix: check allowed domains for social logins

### PR DESCRIPTION
**Pull request by berry-13**
## Summary

added check of allowed domains for social login

## Change Type

- [x] Bug fix (non-breaking change which fixes an issue)

## Testing

tested if every social login works properly

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.

### CODE REVIEW

**Comment by badcom** [comment]
What's missing to merge this?

**Comment by badcom** [comment]
@danny-avila Please review this 😊

**Comment by danny-avila** [comment]
> @danny-avila Please review this 😊

Sorry for the long wait on this @badcom  want to get this done

**Comment by badcom** [comment]
Appreciate it :)

**Comment by Berry-13** [comment]
@danny-avila tests fixed!

**Comment by danny-avila** [comment]
See comment here: https://github.com/danny-avila/LibreChat/pull/1734

**Pull request closed without merging**
