### PR TITLE
📥 feat: Import Conversations from LibreChat, ChatGPT, Chatbot UI

### PR DESCRIPTION
**Pull request by DenisPalnitsky**
## Summary
[Issue](https://github.com/danny-avila/LibreChat/issues/1660)
Import conversation from Json (ChatGPT, Chatbot-ui and Librechat). 

Important design points:
- Agenda is used as a job scheduler to process imports in asynchronous manner 
- the type of file that is imported file is detected automatically so that the user does not have to make that decision. The detection algorithm is extremely naive but should work with current number of supported import files
- poling should be used on a client to query for import job status
 

### Diagram 
```mermaid
graph TB
  linkStyle default fill:#ffffff

  subgraph diagram ["Import Service - Dynamic"]
    style diagram fill:#ffffff,stroke:#ffffff

    subgraph 2 [Import Service]
      style 2 fill:#ffffff,stroke:#9a9a9a,color:#9a9a9a

      10["<div style='font-weight: bold'>JobScheduler</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div>"]
      style 10 fill:#dddddd,stroke:#9a9a9a,color:#000000
      12["<div style='font-weight: bold'>/api/convos/import indpoint</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div>"]
      style 12 fill:#dddddd,stroke:#9a9a9a,color:#000000
      16["<div style='font-weight: bold'>/api/convos/import/jobs endpoint that returns status of import job</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div>"]
      style 16 fill:#dddddd,stroke:#9a9a9a,color:#000000
      3["<div style='font-weight: bold'>MongoDB</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div><div style='font-size: 80%; margin-top:10px'>Stores all conversations</div>"]
      style 3 fill:#dddddd,stroke:#9a9a9a,color:#000000
      4["<div style='font-weight: bold'>ImportBatchBuilder</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div><div style='font-size: 80%; margin-top:10px'>Packs all conversations into<br />message and conversation<br />batches</div>"]
      style 4 fill:#dddddd,stroke:#9a9a9a,color:#000000
      6["<div style='font-weight: bold'>importerProviderConvo</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div><div style='font-size: 80%; margin-top:10px'>Instance of importer<br />importChatGtpConvo,<br />importChatBotUiConvo or<br />importLibreChatConvo</div>"]
      style 6 fill:#dddddd,stroke:#9a9a9a,color:#000000
      8["<div style='font-weight: bold'>getImporter</div><div style='font-size: 70%; margin-top: 0px'>[Container]</div><div style='font-size: 80%; margin-top:10px'>Detects what type of import<br />file is use (chatGpt,<br />Chatbot-ui, Librechat)</div>"]
      style 8 fill:#dddddd,stroke:#9a9a9a,color:#000000
    end

    1["<div style='font-weight: bold'>Client</div><div style='font-size: 70%; margin-top: 0px'>[Person]</div>"]
    style 1 fill:#dddddd,stroke:#9a9a9a,color:#000000

    1-. "<div>1. Sends import file to</div><div style='font-size: 70%'></div>" .->12
    12-. "<div>2. Creates a job with file<br />content in</div><div style='font-size: 70%'></div>" .->10
    10-. "<div>3. Triggers function</div><div style='font-size: 70%'></div>" .->8
    8-. "<div>4. Creates importer instance<br />based on file content</div><div style='font-size: 70%'></div>" .->6
    6-. "<div>5. Creates message and<br />conversation batches using</div><div style='font-size: 70%'></div>" .->4
    4-. "<div>6. Stores conversations and<br />messages in</div><div style='font-size: 70%'></div>" .->3
    1-. "<div>7. Polls for jobs status<br />until the status is success<br />or failure</div><div style='font-size: 70%'></div>" .->16
    16-. "<div>8. Polls for job status</div><div style='font-size: 70%'></div>" .->10
  end
```
## UI

data-import-option
imported-successfully

## Change Type

Please delete any irrelevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Translation update
- [x] Documentation update

## Testing

The examples of exported conversations could be found in `/api/server/utils/import/__data__` directory. 
Apart from unit-tests the functionality were tested on conversation files of ~5Mb size.

## Checklist

Please delete any irrelevant options.

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.
- [x] New documents have been locally validated with mkdocs

### CODE REVIEW

**Comment by danny-avila** [comment]
Hey @DenisPalnitsky thanks for taking a look at this! This is a great feature I look forward to seeing myself. There is lots to do so I can't get to everything at once, so I appreciate you taking a look at this.

I took a quick glance and there are some issues with the approach, and I will use this opportunity to outline my ideas on how to optimize and design this based on long-term thinking for the project.

I don't know about you, but from before I made and started heavily using LibreChat (I never use ChatGPT or any other UI anymore), I have conversations in the thousands, especially from December 2022 - February 2023. I can only imagine from users only just discovering the project, so some things will prevent future headache now.

1. MongoDB batch/bulk operations should be used. Mongoose has a helpful SDK for these
    - On this point, there should be database controllers designed to do this for messages, conversations, similar to how they exist now, having in mind that a complete refactor could happen one day where Mongo isn't our only database solution. This may or may not ever happen, but I would like to decouple from mongo-specific code as much as possible.

2. A job queue system would be ideal
     - This helps fight against potential server congestion of many users importing. Speaking of npm libraries: based on our use of mongo, the [agenda](https://www.npmjs.com/package/agenda) lib may help, [Bree](https://www.npmjs.com/package/bree) is also an option. [bull](https://www.npmjs.com/package/bull) is the most popular but I'm not keen on adding Redis as a required dependency for this quite yet.
     - Implementation of this, similar to last point, should have dependency injection in mind, in case a library is replaced later on.

3. Rate limiting must be enforced on the import route
     - This is primarily for use of agenda or Bree as bull may have rate limiting built in.  This is probably the easiest considering there are already examples in the project, and you would need to follow a similar pattern.

**Comment by DenisPalnitsky** [comment]
Hi @danny-avila 
Thanks for taking a look at the PR in advance. I understand you concerns and will try to take them into account however I'm not an expert in JS and do not know the ecosystem that well so my idea was to add this functionality without touching the existing code whenever possible. 
That was the reason behind using existing interface for creating messages and conversations instead of batch updates. That way migration to other db or just changing the internal structure would have to be done only in one place which makes it easier to maintain. Performance wise it should not be a problem as it's one-time task per user. My 5mb conversations file takes 5 seconds on local machine to import. 
That said I'll give 'agenda' a try and set the rate limiting for the route. I'll add those today-tomorrow and then we can see if there is a way forward.
Also if you have a specific suggestions I'm happy to take them into account. As I said, I have not been working with JS and you guidelines would be very helpful. 
Overall, I think it's a useful feature and having it working somehow would be better then nothing 😄

**Comment by DenisPalnitsky** [comment]
@danny-avila In case we use job scheduler for the task, how do you see the implementation of the feedback to the user whether the import succeeded or not?

**Comment by danny-avila** [comment]
> @danny-avila In case we use job scheduler for the task, how do you see the implementation of the feedback to the user whether the import succeeded or not? Are there such examples in the code that I can refer to?

thats a good question. no example exists as we don't have job scheduling yet. 

For the sake of rolling this out sooner rather than later, you can tackle this PR with just points 1, and 2-4 from earlier, you can let me worry about the job queue handling as that could be an iterative improvement for this.

In my opinion, starting this off with bulk/batch operations is more important and easier to implement with what you built out already.

**Comment by DenisPalnitsky** [comment]
@danny-avila  I added batch write, rate limiting and job scheduler. I also added an endpoint to poll for a jobs status. That would be easiest way to implement feedback for now. 
Could you please check if overall structure looks ok. After confirmation I'll add a tests and submit PR for a review.

**Comment by danny-avila** [comment]
> @danny-avila I added batch write, rate limiting and job scheduler. I also added an endpoint to poll for a jobs status. That would be easiest way to implement feedback for now. Could you please check if overall structure looks ok. After confirmation I'll add a tests and submit PR for a review.

I took a quick glance and it looks good to me! Thanks a lot for working on this.

One note about working in the /api workspace. Later in the project, I started making use of JSDocs and typedefs to provide "types" for the CommonJS code. Typing some of the new functions and classes you made will be extremely helpful for me.

For example, this case AI will excel in as well. Prompt it with the relevant code, and say "Please write JSDocs for this function/class, to provide intellisense in VS Code" and you can also give it examples of these definitions from the project.

**Comment by DenisPalnitsky** [comment]
@danny-avila this one is ready for review

**Comment by danny-avila** [comment]
> @danny-avila this one is ready for review

Thank you, hope to review it this week

**Comment by DenisPalnitsky** [comment]
I have not idea why the test is failing. It passes locally. Is there a chance that `MONGO_URI` secret is not defined in Github action secrets?

**Comment by walbercardoso** [comment]
> I have no idea why the test is failing. It passes locally. Is there a chance that `MONGO_URI` secret is not defined in Github action secrets?

Did you put the .env file inside api folder?

**Comment by DenisPalnitsky** [comment]
> Did you put the .env file inside api folder?

yes, if I run tests locally they pass. However on ci they [fail](https://github.com/danny-avila/LibreChat/actions/runs/8723373664/job/23934149011?pr=2355)

**Comment by walbercardoso** [comment]
Seems like some PARAMS is missing at the .env file. can you share the result of npm run test:api from your local computer?

**Comment by DenisPalnitsky** [comment]
> Seems like some PARAMS is missing at the .env file. can you share the result of npm run test:api from your local computer?

Sure 

```
➜ npm run test:api 
(node:79658) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS utils/azureUtils.spec.js
(node:79657) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS app/clients/specs/BaseClient.test.js
(node:79656) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS server/services/Config/loadConfigModels.spec.js
(node:79655) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS app/clients/specs/AnthropicClient.test.js
PASS app/clients/tools/structured/specs/DALLE3.spec.js
(node:79654) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS app/clients/tools/util/handleTools.test.js
PASS server/services/ModelService.spec.js
PASS app/clients/tools/dynamic/OpenAPIPlugin.spec.js
PASS app/clients/document/tokenSplit.spec.js
PASS cache/banViolation.spec.js
PASS app/clients/tools/util/addOpenAPISpecs.spec.js
PASS server/services/AuthService.spec.js
PASS server/services/Config/loadCustomConfig.spec.js
PASS server/utils/handleText.spec.js
PASS utils/tokens.spec.js
PASS app/clients/tools/util/loadSpecs.spec.js
PASS models/tx.spec.js
PASS strategies/validators.spec.js
PASS utils/extractBaseURL.spec.js
PASS app/clients/prompts/formatMessages.spec.js
PASS server/services/AppService.spec.js
PASS app/clients/output_parsers/addImages.spec.js
PASS app/clients/prompts/formatGoogleInputs.spec.js
PASS server/utils/import/importers.spec.js
  ● Console

    console.log
      Conversation Conversation 1. Web Search imported

      at log (server/utils/import/importers.js:120:13)

(node:79653) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS server/services/Endpoints/assistants/initializeClient.spec.js
(node:79652) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS app/clients/specs/PluginsClient.test.js
(node:79651) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS server/services/Endpoints/google/initializeClient.spec.js
(node:79649) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS server/services/Endpoints/gptPlugins/initializeClient.spec.js
(node:79650) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS server/services/Endpoints/openAI/initializeClient.spec.js
(node:79648) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS app/clients/specs/OpenAIClient.test.js
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.

Test Suites: 1 skipped, 30 passed, 30 of 31 total
Tests:       1 skipped, 401 passed, 402 total
Snapshots:   0 total
Time:        4.006 s
Ran all test suites.
```➜ npm run test:api > test.results
(node:79658) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS utils/azureUtils.spec.js
(node:79657) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS app/clients/specs/BaseClient.test.js
(node:79656) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS server/services/Config/loadConfigModels.spec.js
(node:79655) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS app/clients/specs/AnthropicClient.test.js
PASS app/clients/tools/structured/specs/DALLE3.spec.js
(node:79654) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS app/clients/tools/util/handleTools.test.js
PASS server/services/ModelService.spec.js
PASS app/clients/tools/dynamic/OpenAPIPlugin.spec.js
PASS app/clients/document/tokenSplit.spec.js
PASS cache/banViolation.spec.js
PASS app/clients/tools/util/addOpenAPISpecs.spec.js
PASS server/services/AuthService.spec.js
PASS server/services/Config/loadCustomConfig.spec.js
PASS server/utils/handleText.spec.js
PASS utils/tokens.spec.js
PASS app/clients/tools/util/loadSpecs.spec.js
PASS models/tx.spec.js
PASS strategies/validators.spec.js
PASS utils/extractBaseURL.spec.js
PASS app/clients/prompts/formatMessages.spec.js
PASS server/services/AppService.spec.js
PASS app/clients/output_parsers/addImages.spec.js
PASS app/clients/prompts/formatGoogleInputs.spec.js
PASS server/utils/import/importers.spec.js
  ● Console

    console.log
      Conversation Conversation 1. Web Search imported

      at log (server/utils/import/importers.js:120:13)

(node:79653) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS server/services/Endpoints/assistants/initializeClient.spec.js
(node:79652) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS app/clients/specs/PluginsClient.test.js
(node:79651) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS server/services/Endpoints/google/initializeClient.spec.js
(node:79649) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS server/services/Endpoints/gptPlugins/initializeClient.spec.js
(node:79650) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS server/services/Endpoints/openAI/initializeClient.spec.js
(node:79648) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
PASS app/clients/specs/OpenAIClient.test.js
A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.

Test Suites: 1 skipped, 30 passed, 30 of 31 total
Tests:       1 skipped, 401 passed, 402 total
Snapshots:   0 total
Time:        4.006 s
Ran all test suites.

**Comment by walbercardoso** [comment]
> > Seems like some PARAMS is missing at the .env file. can you share the result of npm run test:api from your local computer?
> 
> 
> 
> Sure 
> 
> 
> 
> ```
> 
> ➜ npm run test:api 
> 
> (node:79658) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS utils/azureUtils.spec.js
> 
> (node:79657) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS app/clients/specs/BaseClient.test.js
> 
> (node:79656) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS server/services/Config/loadConfigModels.spec.js
> 
> (node:79655) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS app/clients/specs/AnthropicClient.test.js
> 
> PASS app/clients/tools/structured/specs/DALLE3.spec.js
> 
> (node:79654) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS app/clients/tools/util/handleTools.test.js
> 
> PASS server/services/ModelService.spec.js
> 
> PASS app/clients/tools/dynamic/OpenAPIPlugin.spec.js
> 
> PASS app/clients/document/tokenSplit.spec.js
> 
> PASS cache/banViolation.spec.js
> 
> PASS app/clients/tools/util/addOpenAPISpecs.spec.js
> 
> PASS server/services/AuthService.spec.js
> 
> PASS server/services/Config/loadCustomConfig.spec.js
> 
> PASS server/utils/handleText.spec.js
> 
> PASS utils/tokens.spec.js
> 
> PASS app/clients/tools/util/loadSpecs.spec.js
> 
> PASS models/tx.spec.js
> 
> PASS strategies/validators.spec.js
> 
> PASS utils/extractBaseURL.spec.js
> 
> PASS app/clients/prompts/formatMessages.spec.js
> 
> PASS server/services/AppService.spec.js
> 
> PASS app/clients/output_parsers/addImages.spec.js
> 
> PASS app/clients/prompts/formatGoogleInputs.spec.js
> 
> PASS server/utils/import/importers.spec.js
> 
>   ● Console
> 
> 
> 
>     console.log
> 
>       Conversation Conversation 1. Web Search imported
> 
> 
> 
>       at log (server/utils/import/importers.js:120:13)
> 
> 
> 
> (node:79653) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS server/services/Endpoints/assistants/initializeClient.spec.js
> 
> (node:79652) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS app/clients/specs/PluginsClient.test.js
> 
> (node:79651) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS server/services/Endpoints/google/initializeClient.spec.js
> 
> (node:79649) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS server/services/Endpoints/gptPlugins/initializeClient.spec.js
> 
> (node:79650) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS server/services/Endpoints/openAI/initializeClient.spec.js
> 
> (node:79648) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS app/clients/specs/OpenAIClient.test.js
> 
> A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
> 
> 
> 
> Test Suites: 1 skipped, 30 passed, 30 of 31 total
> 
> Tests:       1 skipped, 401 passed, 402 total
> 
> Snapshots:   0 total
> 
> Time:        4.006 s
> 
> Ran all test suites.
> 
> ```➜ npm run test:api > test.results
> 
> (node:79658) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS utils/azureUtils.spec.js
> 
> (node:79657) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS app/clients/specs/BaseClient.test.js
> 
> (node:79656) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS server/services/Config/loadConfigModels.spec.js
> 
> (node:79655) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS app/clients/specs/AnthropicClient.test.js
> 
> PASS app/clients/tools/structured/specs/DALLE3.spec.js
> 
> (node:79654) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS app/clients/tools/util/handleTools.test.js
> 
> PASS server/services/ModelService.spec.js
> 
> PASS app/clients/tools/dynamic/OpenAPIPlugin.spec.js
> 
> PASS app/clients/document/tokenSplit.spec.js
> 
> PASS cache/banViolation.spec.js
> 
> PASS app/clients/tools/util/addOpenAPISpecs.spec.js
> 
> PASS server/services/AuthService.spec.js
> 
> PASS server/services/Config/loadCustomConfig.spec.js
> 
> PASS server/utils/handleText.spec.js
> 
> PASS utils/tokens.spec.js
> 
> PASS app/clients/tools/util/loadSpecs.spec.js
> 
> PASS models/tx.spec.js
> 
> PASS strategies/validators.spec.js
> 
> PASS utils/extractBaseURL.spec.js
> 
> PASS app/clients/prompts/formatMessages.spec.js
> 
> PASS server/services/AppService.spec.js
> 
> PASS app/clients/output_parsers/addImages.spec.js
> 
> PASS app/clients/prompts/formatGoogleInputs.spec.js
> 
> PASS server/utils/import/importers.spec.js
> 
>   ● Console
> 
> 
> 
>     console.log
> 
>       Conversation Conversation 1. Web Search imported
> 
> 
> 
>       at log (server/utils/import/importers.js:120:13)
> 
> 
> 
> (node:79653) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS server/services/Endpoints/assistants/initializeClient.spec.js
> 
> (node:79652) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS app/clients/specs/PluginsClient.test.js
> 
> (node:79651) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS server/services/Endpoints/google/initializeClient.spec.js
> 
> (node:79649) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS server/services/Endpoints/gptPlugins/initializeClient.spec.js
> 
> (node:79650) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS server/services/Endpoints/openAI/initializeClient.spec.js
> 
> (node:79648) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> 
> (Use `node --trace-deprecation ...` to show where the warning was created)
> 
> PASS app/clients/specs/OpenAIClient.test.js
> 
> A worker process has failed to exit gracefully and has been force exited. This is likely caused by tests leaking due to improper teardown. Try running with --detectOpenHandles to find leaks. Active timers can also cause this, ensure that .unref() was called on them.
> 
> 
> 
> Test Suites: 1 skipped, 30 passed, 30 of 31 total
> 
> Tests:       1 skipped, 401 passed, 402 total
> 
> Snapshots:   0 total
> 
> Time:        4.006 s
> 
> Ran all test suites.

Try to run npm jest [path/filename] where file name is the file that failed

**Comment by danny-avila** [comment]
I'll add a MONGO_URI so hopefully the tests can be run in CI env

**Comment by DenisPalnitsky** [comment]
> I'll add a MONGO_URI so hopefully the tests can be run in CI env

I think I know what could be a problem. Let me try to fix it.

**Comment by DenisPalnitsky** [comment]
It fails [here](https://github.com/danny-avila/LibreChat/blob/199f9f32e66b5090c0f6e2449792434e325c1dab/api/lib/db/connectDb.js#L5) so adding a  dummy MONGO_URI should do the job

**Comment by danny-avila** [comment]
Fixing the package issue, also seeing if I can handle the jest open handles issue, too.

**Comment by danny-avila** [comment]
I actually need to be added as a collaborator to your fork, but the tests are running fine for me locally

**Comment by DenisPalnitsky** [comment]
> I actually need to be added as a collaborator to your fork, but the tests are running fine for me locally

I added you

**Comment by danny-avila** [comment]
@DenisPalnitsky hope you don't mind, I did a force push to the branch, basically applying your updates cleanly over the latest changes from librechat/main

The reason was, I need to be strict about adding packages going forward as some bleeding edge resolutions from npm are breaking changes. You added the additional packages from this PR correctly so it's not an issue, but wanted to rebase to be sure.

You may need to delete your local branch of this PR and check it out after fetching to be sure you're working on top the rebased branch

As for the one test failing, I think this is a symptom of the CI env not picking up the env.test file, which I will spend the next few minutes trying to figure out why exactly (not really an issue with your PR, just something in the workflow file)

**Comment by danny-avila** [comment]
Also FYI you dont need to change this but I'm a bit OCD with module imports lol

The correct order, from shortest line to longest list for npm packages.
then from longest to shortest for types, local or npm
then from longest to shortest for local modules

Will need to add that to contributing docs.

Some of your imports are out of order so will be fixing that as I touch the files eventually

**Comment by DenisPalnitsky** [comment]
@danny-avila that's your codebase, so you have a right and ,actually, obligation to request and do any changes you think are necessary 😉

**Comment by danny-avila** [comment]
Hoping to merge this by end of the weekend.

@DenisPalnitsky any chance you can get exporting done with this PR or after it? Would just be a single route and you can leverage the job worker and maybe same polling, but no worries if not.

**Comment by DenisPalnitsky** [comment]
> Hoping to merge this by end of the weekend.
> 
> @DenisPalnitsky any chance you can get exporting done with this PR or after it? Would just be a single route and you can leverage the job worker and maybe same polling, but no worries if not.

@danny-avila Do you mean exporting of all conversations in one go?

**Comment by danny-avila** [comment]
> > Hoping to merge this by end of the weekend.
> > @DenisPalnitsky any chance you can get exporting done with this PR or after it? Would just be a single route and you can leverage the job worker and maybe same polling, but no worries if not.
> 
> @danny-avila Do you mean exporting of all conversations in one go?

Yeah from a user request. This is a ChatGPT feature, wouldn’t hurt to have especially for users switching databases or something

**Comment by DenisPalnitsky** [comment]
I can do it in a separate PR sometime at the beginning of next week.

**Comment by danny-avila** [comment]
looking to merge today! working on this right now

**Comment by danny-avila** [comment]
so far with my tests (LibreChat imports), noticed this: 

### imported
image

### original
image

## if I make the tree more complex, it's even less favorable results:

### import 
Screenshot 2024-05-01 131903

### original
Screenshot 2024-05-01 131820


it seems parent/child relationships are not maintained (at least for LibreChat imports, testing chatgpt soon). Once fixed, a test for this would be great, too.

I'm going to be working on copying message trees today for another feature, so maybe we can improve this later, not a dealbreaker to merge right now. Feel free to also work on this and we can compare notes.

I'll be fixing the user issue before, as you can also see in screenshots.

**Comment by danny-avila** [comment]
I'm getting an error with a large import from ChatGPT (36 MB JSON file). Trying to see what might be the best course of action here:

Error processing file Error: Failed to schedule job 'import conversation': RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 && <= 17825792. Received 17825794
    at JobScheduler.now (/home/danny/denis-libre/api/server/utils/jobScheduler.js:42:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /home/danny/denis-libre/api/server/routes/convos.js:113:17

**Comment by DenisPalnitsky** [comment]
@danny-avila  Thanks for fixing my bugs and merging this 👍

**Comment by danny-avila** [comment]
> @danny-avila Thanks for fixing my bugs and merging this 👍

Thanks for your hard work and patience on this 🙏

**Pull request merged**
