### PR TITLE
👮feat: moderation text

### LINKED ISSUE #1288: Enhancement: Option to Pre-filter with OpenAI Moderation Endpoint
### Contact Details

_No response_

### What features would you like to see added?

OpenAI provides a free [Moderation Endpoint](https://platform.openai.com/docs/guides/moderation/overview). You can use it to check if what you want to send complies with their policies. An option to toggle such functionality when using OpenAI API would be helpful. It can potentially be further integrated into existing moderation of LibreChat on user behaviors. 

### More details

OpenAI bans accounts for misuse of API. In many cases, the user is unaware of something making OpenAI unhappy. The optional moderation endpoint pre-filter may provide an additional layer of safeguard against accidentally getting banned while using their API.  

In an ideal world, we should be given the chance to choose if and how we want our APIs moderated, but this is what we have now. 

### Which components are impacted by your request?

Endpoints

### Pictures

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by berry-13**
## Summary

Integrate text moderation middleware with OpenAI API for content filtering
It works only with OpenAI or GPTPlugins

### text detected

image

### error with the moderation check (POST request failed, API-key error, bad URL etc...)

image

## Change Type

- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected) 

## Testing

1. Set up environment variables:
```
OPENAI_MODERATION should be set to 'true' to activate moderation
OPENAI_MODERATION_REVERSE_PROXY (optional) can be set to a custom moderation API endpoint.
OPENAI_MODERATION_API_KEY should contain a valid API key for OpenAI's moderation service.
```
2. Create test cases with various text inputs, including both clean and inappropriate content
3. Send HTTP requests with test cases to the server

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.

### CODE REVIEW

**Review by danny-avila — CHANGES_REQUESTED** [review]
It's concerning that the gptPlugins has so many changes. Please discard the changes to both `openAI` and `gptPlugins` modules, and start over with the following simple change that should go before the route logic in the same files:

`router.use(moderateText);`

**Comment by danny-avila** [comment]
Also you need to do this for the edit routes too.

**Comment by danny-avila** [comment]
Lastly, dotenv.md and .env.example need updating when introducing environment variables

**Comment by fuegovic** [comment]
> Lastly, dotenv.md and .env.example need updating when introducing environment variables

It's already included in dotenv.md (I included it in the big doc refactor to prevent doc conflicts with this PR) 
image

**Comment by danny-avila** [comment]
> > Lastly, dotenv.md and .env.example need updating when introducing environment variables
> 
> It's already included in dotenv.md (I included it in the big doc refactor to prevent doc conflicts with this PR) image

oh ok thank you for pointing that out

**Review by danny-avila — APPROVED** [review]

**Pull request merged**
