### PR TITLE
Added podman installation instructions. Updated dockerfile to stub env

### PR DESCRIPTION
**Pull request by f1yn**
# Pull Request Template

## Summary

- I added documentation for podman based installation, including auto start, backups, and updates.
- I renamed the old docker instructions to docker compose - as it's not technically docker instructions.
- I updated the main Dockerfile to use a few less layers, and to stub out `.env` within the image if one wasn't created in source. I found that the container would crash if `.env` is missing.

## Change Type

Please delete any irrelevant options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Documentation update 

## Testing

Please describe your test process and include instructions so that we can reproduce your test. If there are any important variables for your testing configuration, list them here.

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [ ] ~I have written tests demonstrating that my changes are effective or that my feature works~
- [ ] ~Local unit tests pass with my changes~
- [ ] ~Any changes dependent on mine have been merged and published in downstream modules.~

### CODE REVIEW

**Comment by f1yn** [comment]
Resolves #785

**Comment by danny-avila** [comment]
Awesome, thanks very much! I will have to test the change to dockerfile with compose.

One thing, it will not show up in docs.librechat.ai without editing mkdocs.yml at the root of the project

**Review by fuegovic — CHANGES_REQUESTED** [review]
if you rename or add docs, you need to update the table of contents in `readme.md` and also in `mkdocs.yml`

see for details: https://github.com/danny-avila/LibreChat/blob/main/docs/contributions/documentation_guidelines.md

**Review by danny-avila — APPROVED** [review]

**Comment by danny-avila** [comment]
> if you rename or add docs, you need to update the table of contents in `readme.md` and also in `mkdocs.yml`
> 
> see for details: https://github.com/danny-avila/LibreChat/blob/main/docs/contributions/documentation_guidelines.md

I mentioned this too, but just tested, and everything looks fine to me. I will add it after this PR

**Pull request merged**
