### PR TITLE
Update Chinese translation

### PR DESCRIPTION
**Pull request by Super12138**
## Change Type

- [x] Bug fix (non-breaking change which fixes an issue)
- Translation update

## Testing

Tested and it works.

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.

### CODE REVIEW

**Review by berry-13 — COMMENTED** [review]
Let's start with the premise that I don't know English, but the correct translation wouldn't be "login with Google," instead of "do the login with Google.". Thank you.

**Comment by Super12138** [comment]
> Let's start with the premise that I don't know English, but the correct translation wouldn't be "login with Google," instead of "do the login with Google.". Thank you.
> 

The main reason is that Chinese is different from English.
In Chinese, people usually put the verb before noun. 
In terms of sentence structure, in the Chinese sentence '使用 Google 登录,' '使用 Google' is the subject, and the predicate is '登录.' It means to use Google to log in to the website.
But if it is translated as 'Google 登录,' the subject is 'Google,' and the predicate is '登录.' This translation might not be very clear and could potentially be misunderstood as Google being able to log in.

Comparing these translations, the first one is more in line with the Chinese expression.

If you visit the website Gitee(a website similar to GitHub in China) this [login page](https://gitee.com/login), it translate "Login with GitHub" into “使用 GitHub 账号登录”the same as “使用 Google 登录”.
登录 - Gitee.com

**Review by danny-avila — APPROVED** [review]

**Comment by danny-avila** [comment]
thank you!

**Comment by Berry-13** [comment]
> > Let's start with the premise that I don't know English, but the correct translation wouldn't be "login with Google," instead of "do the login with Google.". Thank you.
> > 
> 
> The main reason is that Chinese is different from English.
> 
> In terms of sentence structure, in the Chinese sentence '使用 Google 登录,' '使用 Google' is the subject, and the predicate is '登录.' It means to use Google to log in to the website.
> But if it is translated as 'Google 登录,' the subject is 'Google,' and the predicate is '登录.' This translation might not be very clear and could potentially be misunderstood as Google being able to log in.
> 
> Comparing these translations, the first one is more in line with the Chinese expression.
> 
> If you visit the website Gitee(a website similar to GitHub in China) this [login page](https://gitee.com/login), it translate "Login with GitHub" into “使用 GitHub 账号登录”the same as “使用 Google 登录”.
> 登录 - Gitee.com
> 
> 

Thanks for the explanation!

**Pull request merged**
