### PR TITLE
Add support for octoai and deepinfra

### PR DESCRIPTION
**Pull request by kneelesh48**
# Pull Request Template

⚠️ Before Submitting a PR, Please Review:
- Please ensure that you have thoroughly read and understood the [Contributing Docs](https://github.com/danny-avila/LibreChat/blob/main/.github/CONTRIBUTING.md) before submitting your Pull Request.

⚠️ Documentation Updates Notice:
- Kindly note that documentation updates are managed in this repository: [librechat.ai](https://github.com/LibreChat-AI/librechat.ai)

## Summary

Add support for DeepInfra and OctoAI in librechat.yml

## Change Type

Please delete any irrelevant options.

- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

## Testing

Please describe your test process and include instructions so that we can reproduce your test. If there are any important variables for your testing configuration, list them here.

## Checklist

Please delete any irrelevant options.

- [ ] My code adheres to this project's style guidelines
- [ ] I have performed a self-review of my own code
- [ ] I have commented in any complex areas of my code
- [ ] I have made pertinent documentation changes
- [ ] My changes do not introduce new warnings
- [ ] I have written tests demonstrating that my changes are effective or that my feature works
- [ ] Local unit tests pass with my changes
- [ ] Any changes dependent on mine have been merged and published in downstream modules.
- [ ] A pull request for updating the documentation has been submitted.

### CODE REVIEW

**Comment by kneelesh48** [comment]
@danny-avila can you merge this?

**Comment by danny-avila** [comment]
Can you provide a file for `client/public/assets/deepinfra.png` that is smaller than 50kb? Thanks

**Comment by kneelesh48** [comment]
@danny-avila

**Comment by kneelesh48** [comment]
@danny-avila can you please review this?

**Comment by danny-avila** [comment]
I've closed this because I don't want to add an icon every time there is a new AI service at anyone's whim. I think the current list is enough, and these services aren't popular enough to include them natively to the project. You are free to fork the project and work off of that as you wish.

**Review by SamDc73 — COMMENTED** [review]
hope this would be added

**Pull request closed without merging**
