### PR TITLE
🖌️ feat: Optional Display Username in Messages, UI improvements, and Localization Updates

### PR DESCRIPTION
**Pull request by itzraiss**
## Summary

When the user sends a message, instead of showing 'You' in the sent message, and the agent's name in the received message with whom he is talking, the user's name will be shown, the same one that appears just below in the left corner in Nav. Also added in place of 'You', the translation for its respective language.

## Change Type

- [x] Translation Update
- [x] Added new feature (Preference in Settings Account to username instead of 'You' when sending messages)
- [x] Style Buttons Updated

Username:

Before: 
Captura de tela 2024-01-16 230628

After:
Captura de tela 2024-01-17 195830

Style Buttons:

Now:
image

### CODE REVIEW

**Comment by danny-avila** [comment]
Thanks for this! I would prefer if it was a setting based on preference. Could you add it to Settings under Account? if you need guidance on this, let me know.

**Comment by itzraiss** [comment]
> Thanks for this! I would prefer if it was a setting based on preference. Could you add it to Settings under Account? if you need guidance on this, let me know.

something like this?
Captura de tela 2024-01-18 065055

**Comment by danny-avila** [comment]
Yes except the message should me much shorter and active tense. “Display username in messages”

**Comment by SailFlorve** [comment]
It should not default, because You is what official ChatGPT shows.

**Comment by itzraiss** [comment]
> Thanks for this! I would prefer if it was a setting based on preference. Could you add it to Settings under Account? if you need guidance on this, let me know.

Sorry for the delay in responding. I was at work all day and only managed to address what you asked for tonight. I would have appreciated your guidance; it would have been much quicker and simpler for me. Anyway, here it is, and if you want me to change anything, just let me know. 🙂

**Comment by itzraiss** [comment]
> It should not default, because You is what official ChatGPT shows.

I left it as disabled by default, the only thing I thought would be interesting is that, just like in ChatGPT, the translation of 'You' to its respective language like 'You' in pt-BR.

**Comment by danny-avila** [comment]
> > It should not default, because You is what official ChatGPT shows.
> 
> I left it as disabled by default, the only thing I thought would be interesting is that, just like in ChatGPT, the translation of 'You' to its respective language like 'Você' in pt-BR.

Thanks so much for the work on this. Going to review it now and I can resolve the conflicts. Sorry I couldn't provide guidance earlier on!

**Comment by danny-avila** [comment]
not a big mess but I made a mistake in pushing the resolution of merge conflicts to your repo! 😬

I've started a new PR with your original commits to clean this up, sorry! https://github.com/danny-avila/LibreChat/pull/1592

I would fix your fork's main branch but I don't have access.

**Pull request closed without merging**
