### PR TITLE
🔒 fix: update refresh token handling to use plain token instead of hashed token

### PR DESCRIPTION
**Pull request by berry-13**
## Summary

fix login bug caused by #5077 

## Change Type

- [x] Bug fix (non-breaking change which fixes an issue)

## Testing

Tested login, logout, api operations (like fetch convo and other basic interactions), refresh token logic, reset password 

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.
- [x] A pull request for updating the documentation has been submitted.

### CODE REVIEW

**Review by fuegovic — APPROVED** [review]

**Comment by KiGamji** [comment]
@berry-13 I am experiencing issue with the previous and this fix, getting unlogined each time I refresh the page after logging in.

**Comment by berry-13** [comment]
> @berry-13 I am experiencing issue with the previous and this fix, getting unlogined each time I refresh the page after logging in.

what login strategy are you using?

**Comment by KiGamji** [comment]
> > Email accounts.
> 
> would you mind if we move this chat to a GitHub discussion or a Discord #issue? It'll help me understand better why it's not working for you

sure, I'll create a discord issue in a moment

**Comment by danny-avila** [comment]
@berry-13 if this is creating issues, you should revert your earlier fix. All we needed were sessions to be deleted on password reset

**Comment by KiGamji** [comment]
> @berry-13 if this is creating issues, you should revert your earlier fix. All we needed were sessions to be deleted on password reset

This PR seems to fix the issue with sessions on SSL deployments, unsure about the local ones. We're currently investigating this further on discord issues channel.

**Comment by stanvx** [comment]
I've also found I'm unable to authenticate when using Authentik with OAuth2/OIDC, for now I'm back on the librechat:v0.7.6 image.

**Comment by danny-avila** [comment]
@stanvx Not having issues with OIDC, you are likely using an image that includes the bug

**Comment by stanvx** [comment]
@danny-avila Thanks, I'll do some testing, check the logs, find out which image it started on and make an issue if needed.

**Comment by stanvx** [comment]
Okay, I confirmed on my side of things that I was using the image with the bug, for whatever reason the `librechat-dev:latest` tag wasn't updating, worked fine specifying the specific sha. :+1:

**Pull request merged**
