### PR TITLE
🚫👤feat: delete user from UI

### LINKED ISSUE #1435: Enhancement: Delete user account
### What features would you like to see added?

Currently, it is not possible to delete your own user account.

### More details

It should be possible to delete a user account, preferably from the logged in user itself. I provided a demo access to my boss to convince him to use LibreChat in our company. Now I can't (quickly) get rid of his demo account.

### Which components are impacted by your request?

_No response_

### Pictures

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by berry-13**
## Summary

I've added a "delete account" button. This button deletes all user information, including plugin auths, conversations, presets, keys, transactions, sessions, messages, and user data.

image

image

image

## Change Type

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have commented in any complex areas of my code
- [x] I have made pertinent documentation changes
- [x] My changes do not introduce new warnings
- [x] I have written tests demonstrating that my changes are effective or that my feature works
- [x] Local unit tests pass with my changes
- [x] Any changes dependent on mine have been merged and published in downstream modules.

### CODE REVIEW

**Comment by danny-avila** [comment]
Thank you for this! I will review and test when I get the chance

**Comment by unitedrule** [comment]
Are there plans to integrate this pull request into the main branch?

**Comment by danny-avila** [comment]
> Are there plans to integrate this pull request into the main branch?

It will be part of the v0.7.3 release. Check the milestone: https://github.com/danny-avila/LibreChat/milestone/5

**Comment by KiGamji** [comment]
Please consider making this feature optional.

**Review by danny-avila — APPROVED** [review]

**Comment by danny-avila** [comment]
> Please consider making this feature optional.

It is enabled by default for GDPR compliance, but you can disable it with the env variable:

```bash
ALLOW_ACCOUNT_DELETION=false
```

**Pull request merged**
