### PR TITLE
🪖 feat: Helm Chart

### PR DESCRIPTION
**Pull request by iamNoah1**
# Pull Request Template

## Summary

Add HelmChart to deploy Librechat on Kubernetes.

## Change Type

Please delete any irrelevant options.

- [x] New feature/chore (non-breaking change which adds functionality)
- [x] This change requires a documentation update
- [x] Documentation update

## Testing

Everything I tested is pretty much described in the documentation section. 

## Checklist

Please delete any irrelevant options.

- [x] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] I have made pertinent documentation changes
- [x] New documents have been locally validated with mkdocs

### CODE REVIEW

**Comment by danny-avila** [comment]
Thank @iamNoah1

When I get the chance I will try following your instructions and merge if I can successfully install it.

Also @idachev may want to take a look as he has a chart that works and was thinking of adding it too.

**Comment by iamNoah1** [comment]
@danny-avila @idachev what do you suggest on how to proceed?

**Comment by iamNoah1** [comment]
@bnsd55 I wanna to keep it as simple as possible. For dev reasons having mongodb and redis also included as chart could come in handy, but in my use case I would want to have them externalized.

**Comment by bnsd55** [comment]
@iamNoah1 okay, I tried to run it and got error:

`
> LibreChat@0.7.0 backend
> cross-env NODE_ENV=production node api/server/index.js
node:buffer:325
  throw new ERR_INVALID_ARG_TYPE(
  ^
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at new NodeError (node:internal/errors:405:5)
    at Function.from (node:buffer:325:9)
    at Object.<anonymous> (/app/api/server/utils/crypto.js:4:20)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/app/api/server/utils/index.js:5:21) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Node.js v18.20.0
npm notice 
npm notice New patch version of npm available! 10.5.0 -> 10.5.2
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v10.5.2>
npm notice Run `npm install -g npm@10.5.2` to update!
npm notice `

any idea why?

**Comment by iamNoah1** [comment]
@bnsd55 have a look at this: https://github.com/danny-avila/LibreChat/discussions/651

Seems you haven't configured it correctly.

**Comment by iamNoah1** [comment]
@danny-avila can we maybe follow up on this? native support of helm chart would be very nice :) and @idachev did not respond to my question about how they think we should proceed with their PR which is on draft by the way. My suggestion is to go with my PR and adjust as needed.

**Comment by danny-avila** [comment]
Yes, there’s a couple helm charts in open PRs. I don’t have much experience with them otherwise I’d compare, or I can get to studying this when I can

**Comment by danny-avila** [comment]
> @danny-avila can we maybe follow up on this? native support of helm chart would be very nice :) and @idachev did not respond to my question about how they think we should proceed with their PR which is on draft by the way. My suggestion is to go with my PR and adjust as needed.

actually I re-read your comment and I agree with you. we can start off with this one and adjust

**Comment by iamNoah1** [comment]
hei @danny-avila, sorry for delay. I am so bad at catching up on github notifications haha. I am not sure if I understood what you mean by "having it on a separate repo in case others have helm charts on the repo already". I mean I can keep the helm chart support in my fork and keep updating my fork accordingly. 

But I see some value in having it in yours, being the original one. This way new Helm charts could be released side by side with new releases of the docker images.

**Comment by danny-avila** [comment]
Merging this PR here https://github.com/danny-avila/LibreChat/pull/3539

**Pull request closed without merging**
