### PR TITLE
🖌️feat: ScrolltoBottom & Mobile Improvements; Translation Update

### PR DESCRIPTION
**Pull request by itzraiss**
## Summary

Scroll button updated its style and moved its position to the middle as ChatGPT. Settings tab now centralized on mobile, fixed for light mode selection visibility, and updated Brazilian Portuguese translation.

## Change Type

- [x] ScrolltoBottom Style Updated
- [x] Updated Settings Tab, layout, and Responsive.
- [x] Selection Fixed for Light Mode

ScrolltoBottom:
Berfore:
Opera Instantâneo_2024-01-26_120822_raigpt site

After:
Opera Instantâneo_2024-01-26_122136_raigpt site

Settings Tab:
Before:
Opera Instantâneo_2024-01-26_203413_raigpt site

After:
Opera Instantâneo_2024-01-26_203437_localhost

### CODE REVIEW

**Comment by itzraiss** [comment]
@Berry-13 , do you think it would be interesting to create a pull request (PR) or implement one of the two updates I made in this same one: centralizing the settings tab on mobile for any device and fixing a bug where selecting the light mode doesn't display the chosen selection:

Before:
Opera Instantâneo_2024-01-26_203413_raigpt site

After:
Opera Instantâneo_2024-01-26_203437_localhost

**Comment by Berry-13** [comment]
> @Berry-13 , do you think it would be interesting to create a pull request (PR) or implement one of the two updates I made in this same one: centralizing the settings tab on mobile for any device and fixing a bug where selecting the light mode doesn't display the chosen selection:
> 
> Before:
> Opera Instantâneo_2024-01-26_203413_raigpt site
> 
> After:
> Opera Instantâneo_2024-01-26_203437_localhost
> 

yeah, that would be amazing!

**Comment by danny-avila** [comment]
I would say it's better to limit the scope of each PR

> feat: ScrolltoBottom Style, 📱Settings tab now centered on mobile / selection fixed 🐞, 🌍 Updated Translation #1

Each of these should be their own PR. 

Will review this soon, thank you

**Comment by itzraiss** [comment]
> I would say it's better to limit the scope of each PR
> 
> > feat: ScrolltoBottom Style, 📱Settings tab now centered on mobile / selection fixed 🐞, 🌍 Updated Translation #1
> 
> Each of these should be their own PR.
> 
> Will review this soon, thank you

Sure, no problem. I'll close this and create a specific one for each?

**Comment by danny-avila** [comment]
> > I would say it's better to limit the scope of each PR
> > > feat: ScrolltoBottom Style, 📱Settings tab now centered on mobile / selection fixed 🐞, 🌍 Updated Translation #1
> > 
> > 
> > Each of these should be their own PR.
> > Will review this soon, thank you
> 
> Sure, no problem. I'll close this and create a specific one for each?

No worries, just for future reference!

**Comment by danny-avila** [comment]
Will be merging this later today!

**Review by danny-avila — APPROVED** [review]

**Pull request merged**
