### PR TITLE
📝 docs: additions to deployment guide

### PR DESCRIPTION
**Pull request by ido777**
## Summary

Add an Introduction to the deployments guide + a request for the community to help in the process of improving the guides.

## Change Type

Please delete any irrelevant options.

- [X] Documentation update

## Testing

NA

## Checklist

NA

### CODE REVIEW

**Review by fuegovic — DISMISSED** [review]
Thanks a lot! The only request I have at the moment would be with the doc file names. All our docs are using lowercase and short names, you could use `intro.md` or `introduction.md` and `nginx.md` to be more in line with the rest of the documentation.

**Comment by ido777** [comment]
Done

**Review by berry-13 — COMMENTED** [review]
@ido777 also the Cloud Service Introduction and the NGNIX Deployment Guide should be in lower case. Thanks

**Comment by fuegovic** [comment]
And don't forget to update the references to the new file names (e.g. in index.md)

**Comment by ido777** [comment]
Done + I refactored  (hopefully improved)  introduction, Sorry for the burden it creates

**Review by berry-13 — APPROVED** [review]
thank you!

**Review by danny-avila — APPROVED** [review]

**Pull request merged**
