### PR TITLE
Several minor design changes and small edits.

### PR DESCRIPTION
**Pull request by apxgpt**
A few minor design changes, I hope you like them. If not, I will remove the pull requests later, so take a look at how it looks and decide whether to accept it or not. It deviates a bit from the openai standard, but you can make your own changes later and modify some of the icons.

before
image
image

after

image
image

before
image
image
image

after
image
image
image
image

before
image

after
image

# Pull Request Template

## Summary

Please provide a brief summary of your changes and the related issue. Include any motivation and context that is relevant to your changes. If there are any dependencies necessary for your changes, please list them here.

## Change Type

Please delete any irrelevant options.

- [x] Bug fix (non-breaking change which fixes an issue)

## Testing

Please describe your test process and include instructions so that we can reproduce your test. If there are any important variables for your testing configuration, list them here.

## Checklist

- [ ] My code adheres to this project's style guidelines
- [x] I have performed a self-review of my own code
- [x] My changes do not introduce new warnings
- [x] Local unit tests pass with my changes

### CODE REVIEW

**Comment by danny-avila** [comment]
Thanks for your PR. some of these changes are good, but some are reverting back to the old style which I dont think I can merge.

With UI changes, before and after screenshots are helpful to better gauge the changes.

**Comment by mmwong1984** [comment]
IMG_1229
IMG_1228

Little compare to official and LibreChat now…
Although it is nearly the same
BUT
The update is actually great!

**Comment by mmwong1984** [comment]
Btw, the side bar….

**Comment by mmwong1984** [comment]
Btw, the sidebar too…
And some improvements can be added to the home page?
IMG_1230

The “ How can I help you today?” can be changed to Hello, {titlename}. Same to the one above.

**Comment by danny-avila** [comment]
Make a new PR just for the login/registration views, I will only merge those changes

**Pull request closed without merging**
